### ISSUE TITLE
revChatGPT update

### ISSUE THREAD

**Issue by getxd-dev** [Zero6992/chatGPT-discord-bot#100]
Hello,

I wanted to let you know that revChatGPT has just been unarchived and updated with a Cloudflare bypass feature. Could you please implement this in the bot?

**Comment by ksvslk** [comment]
YES! Do it!

**Comment by aW3ikun** [comment]
Waiting for Zero to update.

**Comment by JasonInd** [comment]
Made a version that uses the new revChatGPT myself you can check out my repo following the link below. I want to give credit to Zero for the idea and inspiring the readme. Feel free to use whilst waiting for Zero to put out an update.
[https://github.com/JasonInd/chatGPT-DiscordBot](url)

**Comment by Zero6992** [comment]
I noticed that a new stable version has just been released and I will try it out and update ASAP

Sorry for the late reply, not in town last two weeks

**Comment by Zero6992** [comment]
The official API is comming soon
