### ISSUE TITLE
"Introduce Yourself" Personality Customization

### ISSUE THREAD

**Issue by mediacutlet** [Zero6992/chatGPT-discord-bot#102]
In the Gif example the user asks the bot to 'introduce itself' which produces a paragraph of seemingly customizable text. When I ask my bot the same thing, the returned result is: 

> Hi, I'm [name]. I'm a [job title] and I've been working in the [industry] for [time period]. I'm passionate about [cause/interest] and I'm always looking for ways to make a difference. In my spare time, I enjoy [hobbies].

How can this be updated?

**Comment by Zero6992** [comment]
The API using currently is GPT3 instead of GPT3.5 using by ChatGPT
