### ISSUE TITLE
运行python3 main.py报错大佬能帮忙看一下是什么问题吗

### ISSUE THREAD

**Issue by Rotel11** [Zero6992/chatGPT-discord-bot#106]
![IMG_20230107_062331](https://user-images.githubusercontent.com/70079656/211110088-231e64c1-e965-425b-b5b3-2de33832bbeb.jpg)

**Comment by Electroniq100** [comment]
Had the same issue, to fix you will need to ass a credit card in your OpenAi account, it won't charge anything if you don't change your plan.

Manage account > Billing > Payement Methods

**Comment by Vovchanok** [comment]
> 

Now it does charge 5$ if I just add the credit card
