### ISSUE TITLE
How to toggle private mode

### ISSUE THREAD

**Issue by JaserJsk** [Zero6992/chatGPT-discord-bot#115]
I really just want to understand how I can toogle private mode.
I have been trying for a while now.

I don't know if the application is broken or if I'm doing something wrong.

**Comment by aW3ikun** [comment]
Typing `/private` to switch to private mode.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/23023918/212244527-b8c909f9-678c-4d4c-a1b2-40fc70999e67.png">
