### ISSUE TITLE
The process is automatically killed

### ISSUE THREAD

**Issue by JaserJsk** [Zero6992/chatGPT-discord-bot#116]
I'm not really a python developer, but I was able to fallow all the steps and install this 
application on my c-panel deployed on a shared hosting server.

The application is working fine but after sometime, the process is just killed.
Is there anything in the code that I can change or add to stop this from happening ?

Here is a screenshot of the issue
![Skärmbild 2023-01-13 150243](https://user-images.githubusercontent.com/25635376/212358564-7e3e346c-a308-441e-8b19-792f3937f715.png)

**Comment by Zero6992** [comment]
'Killed' usually indicates that your computer terminated the program due to insufficient resources, typically memory shortage

Are there any other processes running on your server?
