### ISSUE TITLE
Error: I think there are something went wrong. Please try again later!

### ISSUE THREAD

**Issue by elliotpollaro** [Zero6992/chatGPT-discord-bot#12]
I keep getting the discord bot saying this error when I ask it a question: 

Error: I think there are something went wrong. Please try again later! 
--

Other error:
('Response is not in the correct format', "Service unavailable: Our services aren't available right now We're working to restore all services as soon as possible. Please check back soon.")

**Comment by Zero6992** [comment]
There must be some issue with chatGPT. Will the same error happen if you try again later?

**Comment by elliotpollaro** [comment]
This is correct. Issue with chatGPT. It's working now
