### ISSUE TITLE
Prompt repeat Fix

### ISSUE THREAD

**Issue by OsbornVentures** [Zero6992/chatGPT-discord-bot#123]
Hello Zero6992 your recent commit to fix prompt repeats unfortunately did not work.
here's a workaround that is cleaner looking and works well without a starting prompt. 
I could not debug your starting prompt repeat error. 
response = f"**{message.user.display_name}** said or asked *{user_message}*. {await responses.handle_response(user_message)}"

**Comment by Zero6992** [comment]
Fixed and updated to ChatGPT API
