### ISSUE TITLE
Bot stopped functioning overnight

### ISSUE THREAD

**Issue by dewmguy** [Zero6992/chatGPT-discord-bot#125]
I had the bot working last night, perfectly. Friends and I played with it for a few hours.

This afternoon, I tried using it, and it doesn't seem to recognize the commands anymore. I have tried restarting the bot. It appears active and has a status of "Watching /chat | /help"

I use tmux to keep the session alive.

![image](https://user-images.githubusercontent.com/16745918/214407618-24de1ad8-54f4-4124-ba9c-9462e7b48b8d.png)

![image](https://user-images.githubusercontent.com/16745918/214407505-1e65b84f-8e02-408d-a48f-8b2af2043724.png)

![image](https://user-images.githubusercontent.com/16745918/214409069-9ce936e4-e921-4a49-b5b1-108964d28954.png)

**Comment by dewmguy** [comment]
I added a prompt to the `starting-prompt.txt` file and rebooted and it's working normally again.

**Comment by xenouch** [comment]
Same thing for me yesturday, reboot do nothing.

Fixed alone, maybe problem with discord API
