### ISSUE TITLE
Problem with the bot

### ISSUE THREAD

**Issue by C4ptainFoxy** [Zero6992/chatGPT-discord-bot#129]
![image](https://user-images.githubusercontent.com/99492756/215270398-f4312047-0544-4206-a814-bc93296ffead.png)

i got this, is anyone know how to fix it ?
<img width="481" alt="uOmNKGFlF4brmFvF" src="https://user-images.githubusercontent.com/99492756/215270393-432e9f60-43bc-4dba-ba4a-0719b29a1f41.png">

**Comment by aW3ikun** [comment]
https://github.com/Zero6992/chatGPT-discord-bot/issues/106

**Comment by Zero6992** [comment]
Duplicated
