### ISSUE TITLE
revChatGPT update with Official API.

### ISSUE THREAD

**Issue by getxd-dev** [Zero6992/chatGPT-discord-bot#131]
Hello, I just wanted to let you know that a new [revChatGPT](https://github.com/acheong08/ChatGPT) update has been released and it now utilizes the official ChatGPT API. It now also supports Async and has no ratelimits and it's completely free. It would be cool if you update the bot to that version. Thanks!

**Comment by Zero6992** [comment]
I've noticed, but the answers seem not to come from the ChatGPT model, more similar to GPT-3, maybe openAI patched that

**Comment by Zero6992** [comment]
Now using the official ChatGPT API"
