### ISSUE TITLE
openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by Zero6992** [Zero6992/chatGPT-discord-bot#134]
https://github.com/acheong08/ChatGPT/issues/523

Move to using the GPT-3 model until OpenAI releases its official API

**Comment by Strachi-sama** [comment]
Yes please :(

**Comment by bacchus929** [comment]
I have the same issue it did work for a maybe 2 requests and then stopped

**Comment by Zero6992** [comment]
Refer here for updates

https://github.com/acheong08/ChatGPT/issues/533
