### ISSUE TITLE
Is it possible to chat directly with the bot, without always typing "/chat " at the beginning

### ISSUE THREAD

**Issue by cary-sas** [Zero6992/chatGPT-discord-bot#142]
Is it possible to chat directly with the bot (maybe just rely on the bot), without always typing "/chat " at the beginning ( I am using Phone, and type / will always switch to digit and special character page, then I need to switch back, that's inconvenient)? 
if there is any setting to achieve this, that will be very helpful to me.

**Comment by Kristiteli** [comment]
I would love this as well. for some reason I can not copy into /chat message window so I would like the bot to respond to every message I send in my discord server. Can you add that as an option please? Or let me know what I can change in the code to make that possible. Ive been trying to make it work for hours :D

**Comment by Zero6992** [comment]
you can now directly chat to the bot using `/replyall` mode
