### ISSUE TITLE
Direct questions 

### ISSUE THREAD

**Issue by Amalbro07** [Zero6992/chatGPT-discord-bot#145]
How can i ask questions directly without using /chat

**Comment by Zero6992** [comment]
Only /chat is available currently

You want to directly chat to the bot or use `@bot` ?

**Comment by Amalbro07** [comment]
Directly

**Comment by Zero6992** [comment]
you can now directly chat to the bot using `/replyall` mode

**Comment by Amalbro07** [comment]
Loved it!
