### ISSUE TITLE
Docker issue after few minutes

### ISSUE THREAD

**Issue by TaijiMonster** [Zero6992/chatGPT-discord-bot#146]
After few minutes it will not answer if is using docker, please check the code?

**Comment by Zero6992** [comment]
fixed, thanks!

**Comment by TaijiMonster** [comment]
Thanks but it's still the same :(

**Comment by Zero6992** [comment]
Make sure to download the latest code and rebuild a new docker image

It's working fine in my both environment, windows 10 and M1 MacOS

**Comment by TaijiMonster** [comment]
> Make sure to download the latest code and rebuild a new docker image
> 
> It's working fine in my both environment, windows 10 and M1 MacOS

will rebuild form scratch again and try.
