### ISSUE TITLE
Suggestion: Add ChannelID limit

### ISSUE THREAD

**Issue by thisischrys** [Zero6992/chatGPT-discord-bot#15]
Please add discord channelID to config to limit bot to a certain channel(s)
I thought /public /private might handle this but I have no idea what this even does.

**Comment by Zero6992** [comment]
You can config which channels your bot has the ability to access directly from the server setting

Server Settings > Intergrations

**Comment by Zero6992** [comment]
/public is switch to public mode => have the bot reply directly on the channel

/private is switch to private mode =>  the bot's reply can only be seen by who send the message
