### ISSUE TITLE
Error occured when using revChatGPT 1.1.5

### ISSUE THREAD

**Issue by anhdungadg** [Zero6992/chatGPT-discord-bot#151]
I pulled the lasted version with revChatGPT 1.1.5 and this error below has occured.

When I use the code with lib openai 0.25.0, everything worked!

Thanks.

```
ERROR    src.bot -> Error while sending message: type object 'Completion' has no attribute 'acreate'
Traceback (most recent call last):
  File "/home/xxx/chatGPT-discord-bot/src/bot.py", line 25, in send_message
    response = f"{response}{await responses.handle_response(user_message)}"
  File "/home/xxx/chatGPT-discord-bot/src/responses.py", line 21, in handle_response
    response = await chatbot.ask(message)
  File "/home/xxx/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 215, in ask
    completion = await self._get_completion(
  File "/home/xxx/.local/lib/python3.10/site-packages/revChatGPT/Official.py", line 196, in _get_completion
    return await openai.Completion.acreate(
AttributeError: type object 'Completion' has no attribute 'acreate'
```

**Comment by Zero6992** [comment]
Reinstall the requirements and the latest code, then try again. If the error still occurs, please provide your environment and the version of Python you are using. Thank you

**Comment by anhdungadg** [comment]
> Reinstall the requirements and the latest code, then try again. If the error still occurs, please provide your environment and the version of Python you are using. Thank you

Thanks a lot for your suggestion.

Now, I don't remember exactly what I did 😅 I'm trying to:
- Create new environment and clone code again
- Do some stuff with pip: upgrade pip version to 23.x, pip cache remove *, pip install -r requirements.txt --no-cache-dir
- And finally, I think the argument -U to install package with lastet version help me solving the proplem.
