### ISSUE TITLE
you can now directly chat to the bot using `/replyall` mode

### ISSUE THREAD

**Issue by cary-sas** [Zero6992/chatGPT-discord-bot#154]
How upgrade the bot to new version? I already git pull your new verison, and then re-install the program, but in my existed bot, I still cannot see the new "/replyall"
 
_Originally posted by @Zero6992 in https://github.com/Zero6992/chatGPT-discord-bot/issues/142#issuecomment-1420253021_

**Comment by 53810** [comment]
#157

**Comment by Eduar21** [comment]
When you activate this command, if the bot is on another server, it will reply to messages on both and on all channels. Is there a way to prevent that from happening?

**Comment by Eduar21** [comment]
When you activate this command, if the bot is on another server, it will reply to messages on both and on all channels. Is there a way to prevent that from happening?
