### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by GolemKing22** [Zero6992/chatGPT-discord-bot#16]
![image_2022-12-07_194407145](https://user-images.githubusercontent.com/115667278/206268654-6790b6f8-1e56-4712-b459-15ab07e254f8.png)
when I try to run the code I get this error message

**Comment by Zero6992** [comment]
You do not have the dependencies installed  `pip install -r requirements.txt`

btw ChatGPT  is down now, so you might receive an error message from the bot

**Comment by MyreGourem** [comment]
how do I install the dependencies?

**Comment by Zero6992** [comment]
`pip install -r requirements.txt`

**Comment by MyreGourem** [comment]
![image](https://user-images.githubusercontent.com/115667278/206297254-591c0780-dd87-4bc8-b54f-5c6a441a888c.png)
the console didn't accept it

**Comment by Zero6992** [comment]
> ![image](https://user-images.githubusercontent.com/115667278/206297254-591c0780-dd87-4bc8-b54f-5c6a441a888c.png)
> 
> the console didn't accept it

You should reopen a terminal and run it again
