### ISSUE TITLE
Error on Step 3: Run the bot on the desktop

### ISSUE THREAD

**Issue by h3clikejava** [Zero6992/chatGPT-discord-bot#161]
(base) ubuntu:~/Documents/chatGPT-discord-bot-0.6.6$ python main.py 
Traceback (most recent call last):
  File "/home/xxx/Documents/chatGPT-discord-bot-0.6.6/main.py", line 1, in <module>
    from src import bot
ImportError: cannot import name 'bot' from 'src' (/home/xxx/anaconda3/lib/python3.9/site-packages/src/__init__.py)

What's that mean? How can i fix it?

**Comment by Zero6992** [comment]
Please provide your python version and environment

**Comment by chroniclex** [comment]
I'm having the same issue running python 3.9.13. I received no errors installing the requirements.

**Comment by chroniclex** [comment]
I figured out the issue. the instructions are mixing python 2 and python 3 commands. if you run pip3 install -r requirements.txt it will install the modules for python3 so that python3 main.py will then work properly
