### ISSUE TITLE
Can have more elaboration on Step 3?

### ISSUE THREAD

**Issue by crzran** [Zero6992/chatGPT-discord-bot#162]
Hi, im not really a programmer and i am deeply confused by step 3, this is what i typed.
![image](https://user-images.githubusercontent.com/111409071/217560803-f06c09a3-67c8-4e59-9571-79e9d675550f.png)
However nothing occurs

**Comment by crzran** [comment]
actually im confused about what does this sentence: pip install -r requirements.txt mean

**Comment by RedSnoww12** [comment]
@crzran, you need to run `pip install -r requirements.txt` with python<=3.9 for download the dependencies of the project. Once it's done you can run `python3 main.py` for launch the bot.

Also, you can install docker and go inside the project in command line and just run `docker compose up -d` [https://github.com/Zero6992/chatGPT-discord-bot#step-3-run-the-bot-with-docker](url) (README.md step3 docker).

**Whatever the previous method you choose**, don't forget to rename the `config.dev.json` file to `config.json` and to put inside the token of your bot discord then your api key of openai.
