### ISSUE TITLE
Recommended using lib Python dotenv

### ISSUE THREAD

**Issue by nthduc** [Zero6992/chatGPT-discord-bot#165]
If you are currently using a JSON file to store your environment variables in your Python project root, you can replace it with using the python-dotenv package. This package allows you to store your environment variables in a .env file, which can be added to your .gitignore file to keep sensitive information like API keys and passwords secure.

To use python-dotenv in your project, first, you need to install it using pip:

```bash
pip install python-dotenv
```
Once installed, add the following code at the beginning of your Python file to load the environment variables from the .env file:
```python
import os
from dotenv import load_dotenv

load_dotenv()
```

**Comment by Zero6992** [comment]
Good, I will check, thank you
