### ISSUE TITLE
About Model

### ISSUE THREAD

**Issue by FuseFairy** [Zero6992/chatGPT-discord-bot#171]
So, now it's still in the form of ChatGPT, but using the GPT-3 model?

**Comment by mauriciopolvora** [comment]
also curious about what would be the difference about using revChatGPT and the openAI paid api

**Comment by Zero6992** [comment]
Correct, the model is a GPT-3 model, but the answers are basically similar to ChatGPT and it also supports context-based conversation

**Comment by Zero6992** [comment]
> also curious about what would be the difference about using revChatGPT and the openAI paid api

 It still belongs to the OpenAI paid API fundamentally, just wrapped differently

You can read the source code of revChatGPT to see what he was done
