### ISSUE TITLE
Where(and how) can i solve problem from 10.02.2023?

### ISSUE THREAD

**Issue by Nikitonz** [Zero6992/chatGPT-discord-bot#172]
https://github.com/Zero6992/chatGPT-discord-bot#2023-02-10-update-chatgpt-model-but-requires-payment
![image](https://user-images.githubusercontent.com/100299461/218146767-cb1a2114-0595-48c5-ba31-554b3b9b983e.png)

**Comment by FuseFairy** [comment]
https://openai.com/api/

**Comment by Zero6992** [comment]
You need to set up your payment information on the OpenAI website
