### ISSUE TITLE
Error, pls help

### ISSUE THREAD

**Issue by lolidrocher** [Zero6992/chatGPT-discord-bot#173]
![image](https://user-images.githubusercontent.com/84981101/218171083-74752a44-a6d5-4c72-aa42-747c82c39401.png)
![image](https://user-images.githubusercontent.com/84981101/218171213-4d9d7334-bd30-4ffa-9862-38d1a21c473b.png)

**Comment by Zero6992** [comment]
What's your python version

**Comment by Zero6992** [comment]
python version need >= 3.9

**Comment by lolidrocher** [comment]
ok
