### ISSUE TITLE
How to get access to the chatgpt api?

### ISSUE THREAD

**Issue by chadexplains** [Zero6992/chatGPT-discord-bot#177]
It looks like the engine you are using (in dev) is the text-davinci-003 model -- how do we get access to the chatgpt (question and answer) model?

**Comment by FuseFairy** [comment]
https://github.com/Zero6992/chatGPT-discord-bot/issues/171#issuecomment-1426643936

There is an answer here, so the actual CPT-3 model is now used, but the effect is similar to ChatGPT.
