### ISSUE TITLE
[Feature Request] Rewrite it so it accepts revChatGPT.V1

### ISSUE THREAD

**Issue by mauriciopolvora** [Zero6992/chatGPT-discord-bot#185]
Hello, since revChatGPT.V1 has been working for a while do you have any ideas of re-writting the code so that it supports this wrapper? 
Only downside is that it is not using asyncio but it would make it so that no paid model is needed.

**Comment by Zero6992** [comment]
Thank for the notice first

Actually I have been following the updates, but it was not really stable before, so I'll watch for a while

**Comment by FuseFairy** [comment]
I tried, but v1 not support async func, so is not suitable for use in discord bot. I think

**Comment by Zero6992** [comment]
> I tried, but v1 not support async func, so is not suitable for use in discord bot. I think

Ture
