### ISSUE TITLE
Please include a temperature setting for the model if possible.

### ISSUE THREAD

**Issue by skoinks** [Zero6992/chatGPT-discord-bot#194]
Pretty much that. I'd like to make the model behave with a bit more creativity, as I suspect it is currently set to 0.9 as the default. It would also be nice to be able to change the token length as we can in the playground to control the length of responses. I've got this thing tied up to my bank card after all :)

**Comment by Zero6992** [comment]
I'll check

**Comment by Zero6992** [comment]
GPT-3.5 model doesn't provide the temperature argument
