### ISSUE TITLE
Feature Request: ReplyAll mode in single channel

### ISSUE THREAD

**Issue by 4uditory** [Zero6992/chatGPT-discord-bot#203]
Hello,

ReplyAll mode is a useful feature, but it is kind of obnoxious to have it reply in every single channel on the server. Would it be possible to restrict ReplyAll mode to a single specified channel? Perhaps the channel specified in the .env for starting prompt?

**Comment by RocketGod-git** [comment]
It should also be confined per user I think. Very rare to have multiple users wanting to build on a prompt in tandem.

**Comment by 4uditory** [comment]
> It should also be confined per user I think. Very rare to have multiple users wanting to build on a prompt in tandem.

For my use case, users do build on the starting prompt together. However, that would not be a bad option either.

**Comment by AleksandrPe** [comment]
That would actually be very helpful, he's trying to answer in other channels, which isn't exactly convenient. I'd be happy to limit it to one channel where I don't have to write /chat

**Comment by Zero6992** [comment]
added it
