### ISSUE TITLE
Weird issue with message formatting. Messages getting clipped off in discord.

### ISSUE THREAD

**Issue by KingBain** [Zero6992/chatGPT-discord-bot#206]
Not sure if this is the actual issue, but I've noticed that some responses from the bot are cut off when its echoed in to the discord channel. 

Looking at the conversation history in he chatgpt website shows the full text.

Have others seen this issue ?

**Comment by KingBain** [comment]
As an example. 

![image](https://user-images.githubusercontent.com/367922/221427169-de8a070d-e534-4677-aa7a-7af27e73852d.png)


in the gpt conversation history 

![image](https://user-images.githubusercontent.com/367922/221427187-72c3eb70-06e6-41ef-ae3d-f7fa3bf2efe3.png)

maybe this is a formatting issue ?

**Comment by Zero6992** [comment]
Resolved here: 

https://github.com/Zero6992/chatGPT-discord-bot/pull/209

**Comment by KingBain** [comment]
Would like to mention this issue is back with the latest build

**Comment by Arusina** [comment]
I have the same issue with the latest version
![grafik](https://user-images.githubusercontent.com/45320603/224566708-a79add11-0c88-4faf-8165-211494ff4f10.png)
