### ISSUE TITLE
ERROR - send_message - Error while sending message: Field missing. Details:

### ISSUE THREAD

**Issue by lintangtimur** [Zero6992/chatGPT-discord-bot#208]
ERROR - send_message - Error while sending message: Field missing. Details: {'detail': 'Something went wrong, please try reloading the conversation.'}

suddenly appear this

**Comment by Zero6992** [comment]
The issue lies with revChatGPT and has been resolved here https://github.com/acheong08/ChatGPT/pull/957

I just updated to the latest requirement, and updating revChatGPT to version 2.3.18 should fix it.
