### ISSUE TITLE
Recommended Add Feature Highlight Text it Responds as Code

### ISSUE THREAD

**Issue by nthduc** [Zero6992/chatGPT-discord-bot#210]
**Adding the Highlight feature when the response is Code in the block, will help us copy the code more easily and look better**

![Screenshot 2023-03-01 153651](https://user-images.githubusercontent.com/111686710/222086852-abaad502-3b87-4364-86be-2ef5e786a4f1.png)
![Screenshot 2023-03-01 153842](https://user-images.githubusercontent.com/111686710/222087300-bd7d1dc6-086e-4d11-b812-8024fddc36f9.png)

**Comment by nthduc** [comment]
It Mistake

**Comment by Zero6992** [comment]
It's hard to add this feature because the messages returned by the ChatGPT model do not provide the language category used by that code block.

**Comment by nthduc** [comment]
you can train bot so it can return block code
