### ISSUE TITLE
ImportError: cannot import name 'AppCommandOptionType' from 'discord.enums'

### ISSUE THREAD

**Issue by Vovchanok** [Zero6992/chatGPT-discord-bot#211]
Hello. 
Should we use only 3.9 python? 
Please suggest. 
<img width="1282" alt="Снимок экрана 2023-03-01 в 3 06 50 PM" src="https://user-images.githubusercontent.com/113111637/222135426-cbe83e9e-cdd4-472e-834a-5866190f41f8.png">
Thank you.

**Comment by Zero6992** [comment]
inactive issue
