### ISSUE TITLE
OpenAI Official API

### ISSUE THREAD

**Issue by BoredMind** [Zero6992/chatGPT-discord-bot#213]
Any intention of allowing the use of the official API?  Given that I pay for ChatGPT and would like to not have my account banned, I would prefer to use the official API.  Yesterday OpenAI made a public post about using unofficial APIs.

`Using bots, scripts, or unofficial ChatGPT APIs to bypass protections on the chat.openai.com website is both a violation of our terms of service and is unsafe. For a secure experience, please stick to the official API provided at https://platform.openai.com/. Violations may result in a ban.`

**Comment by frorayz** [comment]
> Any intention of allowing the use of the official API? Given that I pay for ChatGPT and would like to not have my account banned, I would prefer to use the official API. Yesterday OpenAI made a public post about using unofficial APIs.
> 
> `Using bots, scripts, or unofficial ChatGPT APIs to bypass protections on the chat.openai.com website is both a violation of our terms of service and is unsafe. For a secure experience, please stick to the official API provided at https://platform.openai.com/. Violations may result in a ban.`

I would be heavily interested in this also!

**Comment by Zero6992** [comment]
I have integrated the new API, but there may be some unknown bugs

documentation updates are still in progress
