### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT.V3'

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#215]
Getting this error when trying to run

```
python3 main.py
Traceback (most recent call last):
  File "/home/rayz/HawkyGPT/main.py", line 1, in <module>
    from src import bot
  File "/home/rayz/HawkyGPT/src/bot.py", line 4, in <module>
    from src import responses
  File "/home/rayz/HawkyGPT/src/responses.py", line 2, in <module>
    from revChatGPT.V3 import Chatbot
ModuleNotFoundError: No module named 'revChatGPT.V3'
```
Any help would be appreciated again.

**Comment by Zero6992** [comment]
try `python main.py`?

**Comment by Zero6992** [comment]
you can find some solution here #207

**Comment by frorayz** [comment]
> try `python main.py`?

I only have python3 :(

**Comment by frorayz** [comment]
> you can find some solution here #207

I am not sure since I am using linux, not windows. None of those solutions seems to apply to me and I did couple of fresh install now and same error.

**Comment by Zero6992** [comment]
paste the output of `pip freeze | grep revChatGPT`

**Comment by frorayz** [comment]
> `pip freeze | grep revChatGPT`

`revChatGPT==3.0.5`

**Comment by frorayz** [comment]
@Zero6992 Hey any update on this? Is this just me or something?

**Comment by Zero6992** [comment]
You can try using Python 3.10 and reinstalling

I cannot reproduce this error so I don't have better solution

**Comment by frorayz** [comment]
> You can try using Python 3.10 and reinstalling
> 
> I cannot reproduce this error so I don't have better solution

Alright I switched to a different machine and with python3.10 it seems to work. Thank you!
