### ISSUE TITLE
GPT is not using the model?

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#224]
In the .env I told it to use the `gpt-3.5-turbo` engine. But on my usage its using the `gpt-3.5-turbo-0301` which is the old model and will be stopped being supported June 1. How do I get it to use the actual engine?

**Comment by Zero6992** [comment]
I checked the package of revChatGPT and it seems to use `gpt-3.5-turbo` by default

What are the significant differences between `gpt-3.5-turbo-0301` and `gpt-3.5-turbo`? it will help me in my future testing

**Comment by frorayz** [comment]
> I checked the package of revChatGPT and it seems to use `gpt-3.5-turbo` by default
> 
> What are the significant differences between `gpt-3.5-turbo-0301` and `gpt-3.5-turbo`? it will help me in my future testing

<img width="782" alt="Model" src="https://user-images.githubusercontent.com/32178410/223017557-cbcfe590-2347-43e5-bfec-0a91030aa29b.png">

That's the difference, clearly `gpt-3.5-turbo` is superior. But I am not sure if its revChatGPT or the Bot?

**Comment by Zero6992** [comment]
I knew this, I mean how do you distinguish between the two model in conversation?

**Comment by Zero6992** [comment]
nevermind, I saw it on the OpenAI API website

**Comment by Zero6992** [comment]
I believe that the bot is using `gpt-3.5-turbo`, and since the latest version is currently `0301`, and there are no other latest version, so the user experience should be the same

**Comment by frorayz** [comment]
> I believe that the bot is using `gpt-3.5-turbo`, and since the latest version is currently `0301`, and there are no other latest version, so the user experience should be the same

Ah I see weird they just made distinction then. Thank you for the explanation!
