### ISSUE TITLE
Entering a multi-line message

### ISSUE THREAD

**Issue by MuNeNICK** [Zero6992/chatGPT-discord-bot#23]
When using the bot to type a message, it is not possible to send a message with line breaks. Do you have any plans to resolve this?

Thank you in advance.

**Comment by Zero6992** [comment]
I will see if it can support multiline stuff

**Comment by Zero6992** [comment]
Slash commands don't yet support multiline

[#2381](https://github.com/discord/discord-api-docs/issues/2381)

**Comment by Zero6992** [comment]
The easiest way to fix this is to copy and paste from another editor
