### ISSUE TITLE
Bot cannot be activated.2

### ISSUE THREAD

**Issue by Warabimochiy** [Zero6992/chatGPT-discord-bot#235]
![無題33_20230308135421](https://user-images.githubusercontent.com/127176026/223626195-db5520d3-252e-4da1-9ee6-4fedf3a34e91.png)
After completing all the work and trying to start main.py, I got this error Is there a solution?

**Comment by Zero6992** [comment]
You should provide your discord bot token in the `.env` file

**Comment by Zero6992** [comment]
please follow all the steps in README

**Comment by Warabimochiy** [comment]
I may have made a mistake when editing the env file. do you mean "discord_bot_token "〇〇〇〇〇"? I thought I was supposed to delete "discord_bot_token" and enter the token there.

**Comment by Zero6992** [comment]
It should be like this
```
# Discord bot token
DISCORD_BOT_TOKEN="your discord bot token"

# Website ChatGPT authentication
SESSION_TOKEN=""
OPENAI_EMAIL=""
OPENAI_PASSWORD=""

# Official GPT-3.5 authentication
OPENAI_API_KEY=""

# Optional setting
CHAT_MODEL="OFFICIAL"
.
.
.
```

**Comment by Warabimochiy** [comment]
Resolved. Thank you very much.
