### ISSUE TITLE
"This command is outdated"

### ISSUE THREAD

**Issue by takomine** [Zero6992/chatGPT-discord-bot#24]
This error shows up after inputting "/chat" command in discord. I waited at least 15 mins and the problem still occurs.

![image](https://user-images.githubusercontent.com/108466107/206658983-c14ea7a9-12ab-4ab2-983e-91148e3d990b.png)

**Comment by Zero6992** [comment]
Check if your bot's commands have been synced successfully

Server Settings > Intergrations > bot

![image](https://user-images.githubusercontent.com/89479282/206661920-05d4cdda-a858-448d-9924-0369f33bd373.png)

**Comment by takomine** [comment]
It's okay now. It was synced properly.

It happened when I restarted the bot after updating.
