### ISSUE TITLE
Token Usage

### ISSUE THREAD

**Issue by 4uditory** [Zero6992/chatGPT-discord-bot#241]
As the unofficial model is now deprecated, I have incorporated the official API into my instance. I am measuring token usage, and I am concerned about what is being reported in my OpenAI portal. Please see the following screenshot:

![image](https://user-images.githubusercontent.com/19614293/224106345-5e23f758-c3bc-477e-8a59-5c7a26553ee0.png)

I have a pretty considerable starting prompt, so the initial request looks correct. All of the subsequent prompts included only a few words sent through the bot, so I was surprised to see the high token usage reported for the prompt. It appears that the subsequent prompts are including the tokens from all of the previous requests.

My question: is this normal behavior? As the chat continues and significant history is stored, the cost of each request grows significantly.

**Comment by Zero6992** [comment]
This is correct,  which is why the original API does not have direct support for conversations. 

And to support conversations, the API would need to be able to read previous context, which would increase token usage

**Comment by Zero6992** [comment]
inactive issues
