### ISSUE TITLE
How does the discord bot knew where is the bot server located?

### ISSUE THREAD

**Issue by laladui-eth** [Zero6992/chatGPT-discord-bot#242]
I got the bot server up and running on a local mac. And everything is working fine. I recall not setting the bot server IP anywhere on discord settings. How does the discord bot know where my bot server is located at? And what if I run the bot server on a VPS, where should I put the endpoint address on discord bot settings?

**Comment by Zero6992** [comment]
You need to provide the discord bot token when you run the service, and the API will login to the bot via the token, so it doesn't matter where you run the bot at

**Comment by laladui-eth** [comment]
> You need to provide the discord bot token when you run the service, and the API will login to the bot via the token, so it doesn't matter where you run the bot at

Got it.
