### ISSUE TITLE
Chat model (Website ChatGPT) issue

### ISSUE THREAD

**Issue by HusseinAhmed2** [Zero6992/chatGPT-discord-bot#243]
When I change chat model I get this error:  "Error: Something went wrong, please try again later!"

and this in console:  "File /home/src/bot.py", line 33, in send_message
    response = f"{response}{await responses.unofficial_handle_response(user_message)}"
  File "/home/container/src/responses.py", line 23, in unofficial_handle_response
    async for response in unofficial_chatbot.ask(message):
NameError: name 'unofficial_chatbot' is not defined

**Comment by Zero6992** [comment]
Fixed, thanks

 78465ad
