### ISSUE TITLE
Feature Request: Add eval command

### ISSUE THREAD

**Issue by imjimit07** [Zero6992/chatGPT-discord-bot#244]
Please add a command where the can use the bot to evaluate the code given by the user.

**Comment by Zero6992** [comment]
You need to provide more specific about your use cases, ChatGPT already can evaluate code generally

**Comment by ImRohak** [comment]
@imjimit07 Evaluate as in how? Check for errors, give improvement suggestions?

**Comment by imjimit07** [comment]
> @imjimit07 Evaluate as in how? Check for errors, give improvement suggestions?

Yes Check for errors and give solutions

**Comment by Zero6992** [comment]
GPT has already performed well, and you can improve its performance in specific domains through fine-tuning
