### ISSUE TITLE
Only server admin can use /chat command

### ISSUE THREAD

**Issue by laladui-eth** [Zero6992/chatGPT-discord-bot#245]
Everything is working fine. But I noticed only the server admin can use the /chat command. And what is the Step 2 is doing? Step 2: Website ChatGPT authentication - 2 approaches. I didn't follow this step, and it's still working fine. 

How to make it work so every member in discord can use the /chat command?

**Comment by Shadow4-18** [comment]
go to your server settings > roles > default permissions > and turn on use application commands

**Comment by Klansik** [comment]
This doesn't help. Really only admins can use application commands.

**Comment by Zero6992** [comment]
This is an issue related to Discord's permission settings and is not related to this repository.
