### ISSUE TITLE
GPT 4 Released, When will it be integrated?

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#246]
GPT4 just got released, any idea if it will be integrated?

**Comment by nthduc** [comment]
You can sign up for the waiting list here
https://openai.com/waitlist/gpt-4-api

**Comment by frorayz** [comment]
> You can sign up for the waiting list here https://openai.com/waitlist/gpt-4-api

I am already on the list, just wondering if it will be integrated the chat model here.

**Comment by Zero6992** [comment]
I updated revChatGPT to the latest version, but I don't have access to the GPT-4 API, so I can't test it

**Comment by frorayz** [comment]
> I updated revChatGPT to the latest version, but I don't have access to the GPT-4 API, so I can't test it

Thanks for the quick update but I was wondering as how to change the model? because I do not seem to get gpt4 when change the model to gpt4.

**Comment by Zero6992** [comment]
You can modify `GPT_ENGINE` in the `.env` file, I just updated it

**Comment by frorayz** [comment]
> You can modify `GPT_ENGINE` in the `.env` file, I just updated it
Interestingly, still using gpt3.5 in website model?
<img width="290" alt="Env" src="https://user-images.githubusercontent.com/32178410/225246068-73cf9b00-f239-4716-ba5c-3d82168b3689.png">
<img width="668" alt="Model" src="https://user-images.githubusercontent.com/32178410/225246069-8e7461e8-a62b-4003-84e5-0a7a41f1c869.png">

**Comment by Cyphs** [comment]
> Interestingly, still using gpt3.5 in website model? <img alt="Env" width="290" src="https://user-images.githubusercontent.com/32178410/225246068-73cf9b00-f239-4716-ba5c-3d82168b3689.png"> <img alt="Model" width="668" src="https://user-images.githubusercontent.com/32178410/225246069-8e7461e8-a62b-4003-84e5-0a7a41f1c869.png">
> 
> Since I do have access to GPT4 on plus subscription.

Did you figure this out? And are you using the official API or unofficial?

**Comment by frorayz** [comment]
> > Interestingly, still using gpt3.5 in website model? <img alt="Env" width="290" src="https://user-images.githubusercontent.com/32178410/225246068-73cf9b00-f239-4716-ba5c-3d82168b3689.png"> <img alt="Model" width="668" src="https://user-images.githubusercontent.com/32178410/225246069-8e7461e8-a62b-4003-84e5-0a7a41f1c869.png">
> > Since I do have access to GPT4 on plus subscription.
> 
> Did you figure this out? @frorayz I think it's using GPT-4 despite what it says there, not entirely sure though. If you ask it what GPT model it's using on the website, it still says GPT-3 even with GPT-4 selected. This update seemed to improve the response time and stop errors with the unofficial model.

Nope still not sure what its using lol. I know OpenAI did not update their naming thing yet but who knows if its gpt4 or not yet?

**Comment by Zero6992** [comment]
I made some changes, now you can use `gpt-4` engine in unofficial model, but I don't have a plus account, can you test it for me?

**Comment by frorayz** [comment]
> I made some changes, now you can use `gpt-4` engine in unofficial model, but I don't have a plus account, can you test it for me?

Sure I will and report back~

**Comment by Cyphs** [comment]
> I made some changes, now you can use `gpt-4` engine in unofficial model, but I don't have a plus account, can you test it for me?

I just tried it but it seems like it's still 3.5

**Comment by Cyphs** [comment]
Yeah no dice, still 3.5

**Comment by Zero6992** [comment]
Some changes in responses.py too, you can clone the repo again

**Comment by Cyphs** [comment]
I had done that so it was a clean slate, but still 3.5

**Comment by Cyphs** [comment]
And to be clear it keeps using the 3.5 version available to Plus subscribers: 
![image](https://user-images.githubusercontent.com/119499221/225506742-871b1b59-33ea-45f9-b73c-bce4f5a2641d.png)

**Comment by Cyphs** [comment]
![image](https://user-images.githubusercontent.com/119499221/225508608-ae356415-0ed7-4b66-8a80-2f42f691401a.png)
![image](https://user-images.githubusercontent.com/119499221/225508639-2f04b7e4-bf26-4eaf-8daf-5f8ec72dd1e8.png)
![image](https://user-images.githubusercontent.com/119499221/225508706-386d41da-22a2-4d83-a906-d73a2af039a8.png)

**Comment by otangee** [comment]
You forgot to update your requirements.txt. revChatGPT supports GPT4 since v4.0.2.

```diff
diff --git a/requirements.txt b/requirements.txt
index 99d758a..7575d26 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,5 @@
 discord.py==2.1.0
 python-dotenv==0.21.1
-revChatGPT==4.0.0
+revChatGPT==4.0.2
 openai==0.27.0
 asgiref==3.6.0
```

https://github.com/acheong08/ChatGPT/commit/a1a8c381b901d87da0cb76011eeac1d1f89ce314

**Comment by frorayz** [comment]
> I made some changes, now you can use `gpt-4` engine in unofficial model, but I don't have a plus account, can you test it for me?

<img width="843" alt="works" src="https://user-images.githubusercontent.com/32178410/225514949-9c0c3d4a-c99f-499d-b955-9d83850f8da5.png">

Works perfectly. Thanks!

**Comment by Cyphs** [comment]
All good now here with changing revChatGPT to 4.0.2

**Comment by Nesonica** [comment]
> > > Interestingly, still using gpt3.5 in website model? <img alt="Env" width="290" src="https://user-images.githubusercontent.com/32178410/225246068-73cf9b00-f239-4716-ba5c-3d82168b3689.png"> <img alt="Model" width="668" src="https://user-images.githubusercontent.com/32178410/225246069-8e7461e8-a62b-4003-84e5-0a7a41f1c869.png">
> > > Since I do have access to GPT4 on plus subscription.
> > 
> > 
> > Did you figure this out? @frorayz I think it's using GPT-4 despite what it says there, not entirely sure though. If you ask it what GPT model it's using on the website, it still says GPT-3 even with GPT-4 selected. This update seemed to improve the response time and stop errors with the unofficial model.
> 
> Nope still not sure what its using lol. I know OpenAI did not update their naming thing yet but who knows if its gpt4 or not yet?

thanks mate, that worked for me!

![image](https://user-images.githubusercontent.com/12950714/225605976-e176b662-06be-4b8e-9f47-ce017183e01d.png)
