### ISSUE TITLE
Run the bot on desktop Issue

### ISSUE THREAD

**Issue by HanazakiAkarin** [Zero6992/chatGPT-discord-bot#247]
I typed python3 main.py and it said python was not found, i try to disable the shorcut from the manage app execution settings and now it has an error aswell.

PS C:\Users\ADMIN\Desktop\New folder (3)\chatGPT-discord-bot-main> python3 main.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Zero6992** [comment]
https://stackoverflow.com/questions/65348890/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store

**Comment by Zero6992** [comment]
Did you run `pip install -r requirements.txt`?

**Comment by HanazakiAkarin** [comment]
Ah, for some reason it uninstalled when i was trying to reinstall python, i installed it again and it worked. Ty

**Comment by HanazakiAkarin** [comment]
One last question though, How do i re run the bot? I tweaked some code in it and im not sure if it applied

**Comment by HanazakiAkarin** [comment]
Ahh ok tysm, however. Im having trouble with the persona. Does it work if you change her persona/make a new one by editting the setting?

I tried editting it to one of the built in personas. and re ran it. although i dont see much difference, just the standard chatgpt

**Comment by CentenoA** [comment]
Our group's solution was running the code on Docker. Not ideal but nice if your having persistent issues running it normally.
