### ISSUE TITLE
Feature Request: Add role permissions and filters to commands.

### ISSUE THREAD

**Issue by OsbornVentures** [Zero6992/chatGPT-discord-bot#249]
Can we get a way to change who can use what commands via .env?
For example, all members of the lobby can enable reply all this should be an admin only feature I cannot seem to disable via discord permissions and role assignments.

A request limit for certain roles would be nice too.
for example, @everyone can only do like 20 gpt request,5 Dalle prompts. pms disabled
role1 can do 100 gpt request and 25 Dalle prompts pms enabled
role2 500 request and 100 dalle prompts. pms enabled
role3 unlimited. pms enabled.

**Comment by ZoeMeetAgain** [comment]
Restricting which commands can be used can be done through Discord. Open server settings, go to Integrations and click on the bot, here you can set both role and channel permissions.

**Comment by OsbornVentures** [comment]
> I cannot seem to disable via discord permissions and role assignments.



> Restricting which commands can be used can be done through Discord. Open server settings, go to Integrations and click on the bot, here you can set both role and channel permissions.

**Comment by Zero6992** [comment]
Each server has its own set of roles, Discord API cannot restrict the behavior of specific roles
