### ISSUE TITLE
python-dotenv

### ISSUE THREAD

**Issue by FFierce** [Zero6992/chatGPT-discord-bot#253]
how do i fix this 
![image](https://user-images.githubusercontent.com/88373778/225559680-33d50f42-e213-4d44-bbd1-6a1e0ea58ad4.png)

**Comment by Zero6992** [comment]
`pip install python-dotenv==0.21.1  `

**Comment by ImRohak** [comment]
try installing the latest version of python-dotenv

**Comment by Zero6992** [comment]
Your desktop seems to have multiple Python environments, you need to make sure that your program is running in the environment of `python-dotenv==0.21.1`

**Comment by Zero6992** [comment]
Closed due to lack of interaction
