### ISSUE TITLE
can I use fine-tuning mode?

### ISSUE THREAD

**Issue by pinganyiye** [Zero6992/chatGPT-discord-bot#254]
I set my fine-tuning mode in .env file, but it doesn't work. it shows ：
![image](https://user-images.githubusercontent.com/127939939/225572907-b421bcaf-4719-4402-89ba-d5a6d3210f7e.png)
when I start it ,it shows :
![image](https://user-images.githubusercontent.com/127939939/225573100-e5656a3a-38ad-4917-ac0a-6c6843f64c05.png)

**Comment by pinganyiye** [comment]
can someguys help me? thx

**Comment by Zero6992** [comment]
It's not possible currently

I will see if I can add this feature

**Comment by Zero6992** [comment]
The fine-tuning model cannot be accessed through the OpenAI API
