### ISSUE TITLE
[1.1.1] Weird issue with message formatting. Messages getting clipped off in discord.

### ISSUE THREAD

**Issue by thevker** [Zero6992/chatGPT-discord-bot#258]
![335739654_1128020081199142_2854901121980900130_n](https://user-images.githubusercontent.com/93510166/226082650-51b63d00-b4b4-4e65-be81-746b29fb121c.jpg)

Chatgpt dialogue keep cut
please fix
this is new version (1.1.1)

**Comment by Zero6992** [comment]
Probably related to the token limitation in OpenAI API

GPT-3.5 input has a limit of 2048 tokens, which means that if your prompt exceeds this limit, the response may get truncated.

`/reset` can solve your problem temporarily

**Comment by thevker** [comment]
> Probably related to the token limitation in OpenAI API
> 
> GPT-3.5 input has a limit of 2048 tokens, which means that if your prompt exceeds this limit, the response may get truncated.
> 
> `/reset` can solve your problem temporarily

/reset is the same
I see this error on the server

 "error": {
    "message": "0 is less than the minimum of 1 - 'max_tokens'",
    "type": "invalid request error",
    "param": null,
    "code": null
  }
}

**Comment by Zero6992** [comment]
> /reset is the same
> 
> I see this error on the server
> 
> 
> 
>  "error": {
> 
>     "message": "0 is less than the minimum of 1 - 'max_tokens'",
> 
>     "type": "invalid request error",
> 
>     "param": null,
> 
>     "code": null
> 
>   }
> 
> }

Got it, will check

**Comment by Zero6992** [comment]
Can you tell me how to reproduce this error? Does it happen every time or only under specific circumstances

**Comment by thevker** [comment]
> Can you tell me how to reproduce this error? Does it happen every time or only under specific circumstances

every time

**Comment by thevker** [comment]
> Can you tell me how to reproduce this error? Does it happen every time or only under specific circumstances
![未命名](https://user-images.githubusercontent.com/93510166/226145589-33cefac2-d407-4de4-afc1-a467dd227e0a.jpg)

**Comment by thevker** [comment]
version 1.1.2
same error
I get this error after asking a few questions

**Comment by Zero6992** [comment]
Bug fixed in here https://github.com/acheong08/ChatGPT/issues/1200

I haven't tested it yet, but I've updated the requirements. Give it a try and let me know if it works for you
