### ISSUE TITLE
/private won't work for split responses

### ISSUE THREAD

**Issue by Surasia** [Zero6992/chatGPT-discord-bot#264]
On some longer responses, the subsequent messages delivered by the bot are not hidden from others.

![image](https://user-images.githubusercontent.com/74399067/226142575-fd714514-7f24-4093-b69a-3697c4b06c54.png)

**Comment by frorayz** [comment]
> On some longer responses, the subsequent messages delivered by the bot are not hidden from others.
> 
> ![image](https://user-images.githubusercontent.com/74399067/226142575-fd714514-7f24-4093-b69a-3697c4b06c54.png)

This is discord limitation of 2000 message. I think this is being applied to ephemeral messages too.

**Comment by Zero6992** [comment]
I didn't notice this. I'll check if it's possible to fix

**Comment by Zero6992** [comment]
Discord doesn't allow the same interaction to be answered twice, so  it's not possible to make a message private after the first one has been sent :(
