### ISSUE TITLE
Unable to use GPT_ENGINE="gpt-3.5-turbo"

### ISSUE THREAD

**Issue by JimDude7404** [Zero6992/chatGPT-discord-bot#266]
If i put this in it is still using gpt-3.5-turbo-0301

I have confirmed this with my API's usage model. the 0301 varient is much more expensive than the regular varient. Can you fix this bug ASAP

![image](https://user-images.githubusercontent.com/67085206/226144752-467684d5-fda8-4d4c-8754-65fec6a3b20b.png)

**Comment by frorayz** [comment]
> If i put this in it is still using gpt-3.5-turbo-0301
> 
> I have confirmed this with my API's usage model. the 0301 varient is much more expensive than the regular varient. Can you fix this bug ASAP
> 
> ![image](https://user-images.githubusercontent.com/67085206/226144752-467684d5-fda8-4d4c-8754-65fec6a3b20b.png)

GPT 3.5 turbo is that model. That's the latest snapshot of it. That should be the optimized tokens unless you are really using a lot of tokens.

**Comment by Zero6992** [comment]
They are the same model for now
