### ISSUE TITLE
Embedded Messages

### ISSUE THREAD

**Issue by UnPapiChulo** [Zero6992/chatGPT-discord-bot#267]
Hey @Zero6992

Is there any way you could help me modify the code, or let me know how (im really new at this) to make it so the responses (when using "/chat") from the Bot on my discord channel appear as embedded messages? (preferably in the color red)

Thanks in Advance!

**Comment by FuseFairy** [comment]
use this
https://cog-creators.github.io/discord-embed-sandbox/
