### ISSUE TITLE
[Enhancement] Change models?

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#269]
Just like personas, ability to change models would be useful, so I don't have to get two bots or need to mess with the env every time.

**Comment by frorayz** [comment]
@Zero6992 I am sorry but is it possible to add unofficial model's GPT-4? Instead of the API?

**Comment by Zero6992** [comment]
> @Zero6992 I am sorry but is it possible to add unofficial model's GPT-4? Instead of the API?

Just updated, forgot to update the unoffical part last time

**Comment by frorayz** [comment]
Thanks again @Zero6992 <3
