### ISSUE TITLE
gpt-4 error

### ISSUE THREAD

**Issue by fooc-ctrl** [Zero6992/chatGPT-discord-bot#273]
0|chatgpt  | Exception: Error: 404 Not Found {
0|chatgpt  |     "error": {
0|chatgpt  |         "message": "The model: `gpt-4` does not exist",
0|chatgpt  |         "type": "invalid_request_error",
0|chatgpt  |         "param": null,
0|chatgpt  |         "code": "model_not_found"
0|chatgpt  |     }
0|chatgpt  | }
0|chatgpt  |

**Comment by MileyHollenberg** [comment]
Your account on OpenAI needs to have access to the gpt-4 model, you can join the waitlist for that. Without access it will return a 404

**Comment by Zero6992** [comment]
you can join the waitlist here https://openai.com/waitlist/gpt-4-api
