### ISSUE TITLE
Unable to limit bot to a set of channels

### ISSUE THREAD

**Issue by sounddrill31** [Zero6992/chatGPT-discord-bot#276]
# Discord Bot token
DISCORD_BOT_TOKEN="censored"

# Unofficial ChatGPT authentication
SESSION_TOKEN=""
OPENAI_EMAIL=""
OPENAI_PASSWORD=""

# Official GPT-3.5 authentication
OPENAI_API_KEY="censored"

# Optional setting
CHAT_MODEL="OFFICIAL"
GPT_ENGINE="gpt-3.5-turbo" # "gpt-4" if you can access GPT-4 models
LOGGING="True"
REPLYING_ALL="False"
#DISCORD_CHANNEL_ID=""
DISCORD_CHANNEL_ID="channel1inServer1"
DISCORD_CHANNEL_ID="channel2inServer2"

Strangely, It's accepting messages serverwide.

**Comment by Zero6992** [comment]
`DISCORD_CHANNEL_ID` is only used to determine the initial channel for message sending. For permissions, you can go to the bot settings in the Discord app to restrict the channels where the command can be used

**Comment by sounddrill31** [comment]
> `DISCORD_CHANNEL_ID` is only used to determine the initial channel for message sending. For permissions, you can go to the bot settings in the Discord app to restrict the channels where the command can be used

Thanks for the reply, I fixed it thanks to the integrations tab.
