### ISSUE TITLE
Feature request, add a "bot is typing..." indicator

### ISSUE THREAD

**Issue by MileyHollenberg** [Zero6992/chatGPT-discord-bot#277]
Right now when I set the bot to reply all on my personal Discord server I don't have any indication of whether it's actually replying to something. Would be nice to add this indicator just to make it a bit more clear to the user that the API is running

**Comment by Zero6992** [comment]
Discord's response in `reply-all` mode differs from slash command

Only slash commands like `/chat` support the "bot is thinking..." message
