### ISSUE TITLE
Getting access to plugins seems to mess up models?

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#280]
I got access to the browser plugin (model: text-davinci-002-browse):

<img width="684" alt="Browser" src="https://user-images.githubusercontent.com/32178410/227406865-776ad848-9cfd-4258-9e77-cd9ef810f2d8.png">

And it messed up ChatGPT's website default GPT 3.5 model. 
They are now called text-davinci-002-render-sha (Default GPT-3.5)
And text-davinci-002-render-paid (Legacy GPT-3.5)

Is the bot going to address these issues or do I just have to change the .env gpt-model around?

**Comment by Zero6992** [comment]
I don't have the access for that feature yet, so I haven't encountered this issue. Perhaps you can try modifying the `.env` on your own to resolve this issue temporarily

**Comment by frorayz** [comment]
> I don't have the access for that feature yet, so I haven't encountered this issue. Perhaps you can try modifying the `.env` on your own to resolve this issue temporarily

Yea I just did that, for now that will work. Thanks!
