### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Krosskid12** [Zero6992/chatGPT-discord-bot#282]
![image](https://user-images.githubusercontent.com/73221787/227477818-add44429-86c8-4aad-93ec-dda410e160a4.png)
can somebody help me whats the error and solution?

**Comment by Zero6992** [comment]
It would be helpful if you could share additional details about your computer's setup

I suggest opening a new Python environment with conda to prevent any interference from other Python packages that could affect this program
