### ISSUE TITLE
Personas not working

### ISSUE THREAD

**Issue by NostromoUS** [Zero6992/chatGPT-discord-bot#283]
Hi, first of all, great work on this!

I'm using a plus account, gpt-4 model (not API) and personas don't seem to work at all? The responses are essentially the same and super restricted.

Do I need to use the API for that or is there something else?

Thanks

**Comment by shinysocks** [comment]
That is correct, it seems that many personas don't work with GPT-4. Check [here](https://www.jailbreakchat.com) for a `4` next to the name confirming that it works for GPT-4. I will add some of these if they look good.
