### ISSUE TITLE
Feature Request: Reply All & draw

### ISSUE THREAD

**Issue by sfxworks** [Zero6992/chatGPT-discord-bot#284]
I want to be able to use replyall in a channel, but still use the /draw command in the same or other channels

**Comment by Zero6992** [comment]
fixed

**Comment by sfxworks** [comment]
![image](https://user-images.githubusercontent.com/5921035/228552702-ac67f39a-7155-4fbe-ac2d-c4a58e34ca6d.png)
Can you tell me how? Pulled the latest branch and rebuilt. I still get this
