### ISSUE TITLE
Answers cut off after first message

### ISSUE THREAD

**Issue by namion** [Zero6992/chatGPT-discord-bot#29]
When the bot gives a long answer, the answer doesn't roll over to a second message. I've only seen it happen once where the bot sends a 2nd message to finish the answer. Is there any way to fix this?

**Comment by aW3ikun** [comment]
@namion Have you tried typing `continue`?

**Comment by Zero6992** [comment]
This is an issue with OpenAI

In their chat rooms, your dialogue may sometimes be cut off

The current solution is to `continue` the conversation in the next message
