### ISSUE TITLE
Can't launch the Bot error

### ISSUE THREAD

**Issue by solofireflyxdev** [Zero6992/chatGPT-discord-bot#292]
![Screenshot_20230326_085652_com.replit.app.jpg](https://user-images.githubusercontent.com/107917094/227760440-6ad17edf-f738-4751-acaf-1cc6a0bddab3.jpg)

**Comment by ChatGPT-4** [comment]
Working for me fine. What windows version do you use?

**Comment by solofireflyxdev** [comment]
> Working for me fine. What windows version do you use?
> 

I'm using replit.it, that is for mobile and desktop
