### ISSUE TITLE
Feature request: "system" message

### ISSUE THREAD

**Issue by kulkovsky** [Zero6992/chatGPT-discord-bot#295]
First of all, thank you for working on this project. It is incredible.

Using the starting prompt is a great way to kick off the bot. However, when prototyping in the playground, I achieved better results with the system message. (I am using gpt-4 api)

The purpose of the "system" message is to set the context and behavior of the chatbot. It acts like a high-level instruction that the model will try to follow throughout the conversation. By providing this initial message, you're telling the chatbot about its knowledge, expertise, and personality traits. 

Could you implement this feature?

**Comment by Zero6992** [comment]
Hey, thanks for letting me know. I just checked, and it seems possible. I will add this feature in the next version, but I need to check its actual effectiveness.
