### ISSUE TITLE
Error While Changing To Bard Model

### ISSUE THREAD

**Issue by madscientista** [Zero6992/chatGPT-discord-bot#302]
Getting this error when trying to change the model to Bard.

```
2023-03-28 09:23:23 ERROR    src.bot -> Error while switching to the Bard model: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/xx/xxx/src/bot.py", line 221, in chat_model
    client.chatbot = client.get_chatbot_model()
  File "/home/xx/xxx/src/aclient.py", line 40, in get_chatbot_model
    return BardChatbot(session_id=self.bard_session_id)
  File "/home/xx/xxx/hawkygpt/lib/python3.10/site-packages/Bard.py", line 83, in __init__
    self.SNlM0e = self.__get_snlm0e()
  File "/home/xx/xxx/xxxx/lib/python3.10/site-packages/Bard.py", line 90, in __get_snlm0e
    SNlM0e = re.search(r"SNlM0e\":\"(.*?)\"", resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Zero6992** [comment]
Did you fill in the `BARD_SESSION_ID`?

**Comment by ErasedCitizen** [comment]
same issue here

**Comment by Zero6992** [comment]
I don't have access to Bard, so it's difficult for me to do testing, but it seems like the problem is that it's reading nothing from the `BARD_SESSION_ID` in `.env`.

**Comment by ImHack1993** [comment]
> I don't have access to Bard, so it's difficult for me to do testing, but it seems like the problem is that it's reading nothing from the `BARD_SESSION_ID` in `.env`.

same error.
It was workable yesterday 
As bard cookies keep changing
so just update it then will be fine

**Comment by PranavPurwar** [comment]
inactive because no one know the fix

**Comment by Zero6992** [comment]
> > > I don't have access to Bard, so it's difficult for me to do testing, but it seems like the problem is that it's reading nothing from the `BARD_SESSION_ID` in `.env`.
> > 
> > 
> > same error. It was workable yesterday As bard cookies keep changing so just update it then will be fine
> 
> after messing a bit with Bard.py to fix that, I still can't get it to work: `Google Bard encountered an error: b')]}'\n\n103\n[["er",null,null,null,null,400,null,null,null,3],["di",85],["af.httprm",84,"-9101457324592624751",1]]\n25\n[["e",4,null,null,139]]\n'.`

This issue can discuss in #358
