### ISSUE TITLE
Official Version Quota Issue

### ISSUE THREAD

**Issue by PaixHaine** [Zero6992/chatGPT-discord-bot#303]
Hi, first of all I like a lot your work, thx very much for it :)

I've got an issue when I'm trying to chat in official mode, see by yourself : 

`2023-03-28 10:25:14 ERROR    src.aclient -> Error while sending message: 429 Too Many Requests {                       
    "error": {                                                                                                         
        "message": "You exceeded your current quota, please check your plan and billing details.",                     
        "type": "insufficient_quota",                                                                                  
        "param": null,                                                                                                 
        "code": null                                                                                                   
    }                                                                                                                  
}   `

I've got a OpenAI Plus account so i'm a bit regarding this error !

I checked and in my env file i've got everything setup, maybe not correctly I guess (although i'm pretty sure of my credentials...)

Tell me if you want to see my env file :) 

Thx

**Comment by namion** [comment]
Just a guess but are you using the GPT-4 model? In that situation, you would still be restricted by the quota that is in place: 25 messages every 3 hours.

**Comment by Zero6992** [comment]
`official mode` means calling the official API, which requires payment whether or not you have a plus account

**Comment by Zero6992** [comment]
> @namion nope I was using 3.5, standard one, i'm aware of the v4 limitations but still thank you for letting me know ;) 
> 
> 
> 
> 
> 
> > `official mode` means calling the official API, which requires payment whether or not you have a plus account
> 
> 
> 
> Oh damn, I just realized that GPT Plus and paying for the api were two things different, i thought that if you had a plus account would be enough but I guess not !
> 
> 
> 
> Tell me if I'm completely wrong on that but i think i figured it out :)
> 
> 
> 
> Does it means that i have to stick to "website" ones instead of "official" ?
> 
> 
> 
> Thanks you again for your time folks !

Yes, correct
