### ISSUE TITLE
chat bot forgets its personality after reset even tho the settings say anotherwise

### ISSUE THREAD

**Issue by nekohacker591** [Zero6992/chatGPT-discord-bot#312]
![image](https://user-images.githubusercontent.com/73713314/228966687-c1833abe-b062-493f-be2d-e801260c88a9.png)

here is the modified code

![image](https://user-images.githubusercontent.com/73713314/228966572-e77e4ef2-7d89-4c52-8681-2b6ccbb0783d.png)

**Comment by nekohacker591** [comment]
note to creator i only removed some features so fit my needs so it still functions the same its not a issue with the edit but rather a issue with the original code

once you fix the issue i will commit the new code

**Comment by Zero6992** [comment]
fixed
