### ISSUE TITLE
Answers are not written completely

### ISSUE THREAD

**Issue by Arusina** [Zero6992/chatGPT-discord-bot#318]
I have a problem with the messages. When questions are asked, sometimes the message is truncated. 

![grafik](https://user-images.githubusercontent.com/45320603/229312354-2ebe8047-c489-44dc-9661-754f1339f759.png)
![grafik](https://user-images.githubusercontent.com/45320603/229312503-d4148bfe-ced8-4399-87dc-64b45312b0e8.png)

This does not always happen. It doesn't matter in which language (tested in German and English). 

Repoducibility:
Write messages, sometime the error comes. I estimate about 1/5 of the messages are then not complete.

Questions:
I suspect that it breaks off somewhere in the chain from

answer from open ai -> python program -> discord chat 

Is there a way to increase the logging? Is there somewhere to read if the python program is getting the response complete from openai? With this you could start to narrow down the error further.

**Comment by Zero6992** [comment]
which model are you using? Unofficial or official? 
gpt-4 or gpt-3.5?

**Comment by Arusina** [comment]
OPENAI_ENGINE = "gpt-3.5-turbo "
CHAT_MODEL="OFFICIAL"

![grafik](https://user-images.githubusercontent.com/45320603/229352842-53a124b5-1fb7-41f5-ad7f-2bc80c7796ff.png)

The Python is running on Ubuntu 20.04.6 LTS machine with python3.

**Comment by Arusina** [comment]
Updated to the newest version, since then it's working perfectly.
