### ISSUE TITLE
Bot command error

### ISSUE THREAD

**Issue by skygamer1233** [Zero6992/chatGPT-discord-bot#319]
I have this problem when running the bot
![image](https://user-images.githubusercontent.com/123954037/229352896-6f2e4f2c-fbfb-45a8-a0a5-f57690c2364f.png)
![image](https://user-images.githubusercontent.com/123954037/229352922-8f833475-f498-4531-b5c9-5f02ba7fb4b8.png)

**Comment by Artfill008** [comment]
The same garbage, only it works for me on Windows, and through Synology Docker It gives such an error if someone tells me how to solve For example, the command, draw, works.
![image](https://user-images.githubusercontent.com/87469517/229373581-e529c32e-1e5d-4bf4-9dcc-ea4ae1a0824a.png)
![image](https://user-images.githubusercontent.com/87469517/229373654-f06c30b8-4acd-4ded-b7be-2212f2c5df48.png)
![image](https://user-images.githubusercontent.com/87469517/229373680-c98999a6-700e-411d-a465-675cee5b2680.png)


PLEASE, Help!

**Comment by Zero6992** [comment]
try the solution here #230

**Comment by skygamer1233** [comment]
I tried it but still the same problem

**Comment by Zero6992** [comment]
python version?

**Comment by skygamer1233** [comment]
> python version?

Latest version

**Comment by Zero6992** [comment]
inactive issue
