### ISSUE TITLE
better discord implementation

### ISSUE THREAD

**Issue by ziipzaaapM16A4** [Zero6992/chatGPT-discord-bot#32]
instead of /chat how about ping the bot.
and make if able to be on the members list/to be able to chat with it without discord Server.

**Comment by Zero6992** [comment]
By using slash commands in private messages, you can chat with the bot directly 

Just make sure to turn this on 

USER SETTINGS > Privacy & Safety

![image](https://user-images.githubusercontent.com/89479282/206840945-f199fda9-61aa-4068-94c4-d8353a6adba0.png)

**Comment by ziipzaaapM16A4** [comment]
So he did indeed appear on the member list but a ping still does not result in answering my question.

"Allow direct messages from server memebers" was already activated.  
Is it maybe something with the permissions. Since i am not a discord bot power could you text me the full permissions configuration you use the bot?

**Comment by Zero6992** [comment]
The permission of send message in OAuth2 URL Generator?

![image](https://user-images.githubusercontent.com/89479282/206903820-33d03a2a-2c20-4d5b-aa35-23e054eef76e.png)

**Comment by ziipzaaapM16A4** [comment]
ok i gave it the same permissions but i still can't ping the bot with /chat

**Comment by ziipzaaapM16A4** [comment]
So just for clarification. 
I want to reach the bot by typing 
@bot
and not by
/chat

**Comment by Zero6992** [comment]
I believe the difference between the two is not significant, and most Discord bots now use slash commands to interact with it, such as the Midjourney bot
