### ISSUE TITLE
Error while starting the bot

### ISSUE THREAD

**Issue by JuliaNGaminG007** [Zero6992/chatGPT-discord-bot#323]
I am getting this errors while I run the `python3 main.py` command

![Screenshot 2023-04-05 105518](https://user-images.githubusercontent.com/96736018/229989275-b831f548-9c86-4af0-a476-f4f5631836b7.png)

May I know what this error is about and how to fix it?

**Comment by Neillife** [comment]
You need to install openai.
[Critical prerequisites to install](https://github.com/Zero6992/chatGPT-discord-bot#critical-prerequisites-to-install
)

**Comment by JuliaNGaminG007** [comment]
> You need to install openai. [Critical prerequisites to install](https://github.com/Zero6992/chatGPT-discord-bot#critical-prerequisites-to-install)

I already installed the things in requirements.txt but I am still the getting the same error

**Comment by JuliaNGaminG007** [comment]
> I am getting this errors while I run the `python3 main.py` command
> 
> ![Screenshot 2023-04-05 105518](https://user-images.githubusercontent.com/96736018/229989275-b831f548-9c86-4af0-a476-f4f5631836b7.png)
> 
> May I know what this error is about and how to fix it?

Any other suggestions?

**Comment by Zero6992** [comment]
https://stackoverflow.com/questions/25119298/importerror-no-modules-named-but-modules-already-installed-in-dist-packages

**Comment by JuliaNGaminG007** [comment]
> https://stackoverflow.com/questions/25119298/importerror-no-modules-named-but-modules-already-installed-in-dist-packages

Thanx this works!
