### ISSUE TITLE
Auto-Update the project

### ISSUE THREAD

**Issue by JuliaNGaminG007** [Zero6992/chatGPT-discord-bot#334]
Is there a way we could auto update the project in our machine when a new update is pushed into the repo without loosing our own edits?

**Comment by sounddrill31** [comment]
here's the script I use:

```
cd /home/ubuntu
git force-clone https://github.com/Zero6992/chatGPT-discord-bot.git chatGPT-discord-bot


cd /home/ubuntu/chatGPT-discord-bot
python3 main.py
```
It works thanks to the gitignore in the repo, not overwriting my config.

I do not recommend doing it like this, but since I'm just hosting it for fun, there's no consequence to messing something up.

**Comment by JuliaNGaminG007** [comment]
> here's the script I use:
> 
> ```
> cd /home/ubuntu
> git force-clone https://github.com/Zero6992/chatGPT-discord-bot.git chatGPT-discord-bot
> 
> 
> cd /home/ubuntu/chatGPT-discord-bot
> python3 main.py
> ```
> 
> It works thanks to the gitignore in the repo, not overwriting my config.
> 
> I do not recommend doing it like this, but since I'm just hosting it for fun, there's no consequence to messing something up.

Right... exactly what I needed thanks
