### ISSUE TITLE
/draw Mention is broken

### ISSUE THREAD

**Issue by frorayz** [Zero6992/chatGPT-discord-bot#345]
On Desktop it looks broken:
<img width="331" alt="Screen Shot 2023-04-13 at 12 18 46 PM" src="https://user-images.githubusercontent.com/32178410/231822650-99bdadb7-bf15-4302-a3a7-7a2ed8ef15be.png">

On mobile it looks fine:
![IMG_0257](https://user-images.githubusercontent.com/32178410/231823056-21f38c6d-8b84-4955-bd19-b83adf4fb382.jpg)

**Comment by Cyber-Thibaut** [comment]
This is a Discord bug not a bot bug.
