### ISSUE TITLE
Google bard error 

### ISSUE THREAD

**Issue by HusseinAhmed2** [Zero6992/chatGPT-discord-bot#358]
When i use google bard now i get this error

Google Bard encountered an error: b')]}'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n58\n[["di",160],["af.httprm",160,"-2748455247570860733",14]]\n25\n[["e",4,null,null,133]]\n'.

**Comment by frorayz** [comment]
Same +1

**Comment by Zero6992** [comment]
I can't use Google Bard, but I upgraded the relevant packages, so maybe you can try it out

**Comment by frorayz** [comment]
> I can't use Google Bard, but I upgraded the relevant packages, so maybe you can try it out

I have upgraded mine manually and this still happens.

**Comment by Zero6992** [comment]
relevant issue: https://github.com/acheong08/Bard/issues/5

**Comment by Zero6992** [comment]
Error could happens if your browser logged into multiple accounts. Log in from an anonymous webpage and obtain the session token

**Comment by LoremBotsum** [comment]
Same issue, this case should be open

**Comment by nsto2335** [comment]
Any luck yet anyone? having the same issue
