### ISSUE TITLE
Add an option to remove boilerplate text from the result

### ISSUE THREAD

**Issue by pardeike** [Zero6992/chatGPT-discord-bot#36]
ChatGPT answers are just too long for effective usage in a discord channel. And OpenAI has added lots of gatekeeping so the result often contains the same phrases about what it is and why it can’t browse the internet, regardless how one tries to force the AI to not repeat it. 

So a more manual filtering on the bot level could solve this if it is made configurable. 

BTW: excellent work!

**Comment by Zero6992** [comment]
I think it would be difficult to filter the text of what the bot replies

A possible solution would be for you to include "Don't tell me you can't access the internet, don't tell me what you are..." in every prompt you send

**Comment by Zero6992** [comment]
[awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts)

This could be helpful btw

**Comment by pardeike** [comment]
The problem is that OpenAI has added a lot of safe guards against such prefix injection. I constantly get the same extra boilerplate even when trying to prefix with all kind of "don't do X" phrases.

**Comment by Zero6992** [comment]
> The problem is that OpenAI has added a lot of safe guards against such prefix injection. I constantly get the same extra boilerplate even when trying to prefix with all kind of "don't do X" phrases.

I understand that it can be annoying sometimes, but I don't think filtering out responses from bots is a good solution
