### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by ehsrzv** [Zero6992/chatGPT-discord-bot#362]
![Screenshot 2023-04-23 093927](https://user-images.githubusercontent.com/67677822/233820983-80076797-a150-4d91-95ab-78924beacf64.png)
 
Hi Dear Zero6992

How do I fix it?

**Comment by Neillife** [comment]
According to the settings in the [Dockerfile](https://github.com/Zero6992/chatGPT-discord-bot/blob/main/Dockerfile) in the main branch of the repository.
It looks like the possible reasons are as follows:
1. ```rustup``` is not installed correctly.
2. ```ENV PATH="/root/.cargo/bin:${PATH}"``` may cause ```rustup``` not to be found.

https://stackoverflow.com/questions/49676490/when-installing-rust-toolchain-in-docker-bash-source-command-doesnt-work
maybe this will help you.

**Comment by Zero6992** [comment]
Delete the original docker images and then run `docker compose up` again

**Comment by Zero6992** [comment]
inactive issue
