### ISSUE TITLE
TypeError: expected token to be a str, received NoneType instead (I'm not a coder so I'm just following directions)

### ISSUE THREAD

**Issue by elderprice** [Zero6992/chatGPT-discord-bot#363]
I've followed the directions to the T, but it doesn't allow me to start the bot based on the instructions. Upon asking ChatGPT, it says that there is wrong with my discord bot token. However, I literally just copy pasted it. How do I get it to work?

Here's the return after I try to run the bot:

C:\Users\joaqu\Desktop\GPT for Discord\chatGPT-discord-bot-main>python3 main.py
2023-04-23 15:55:12 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "C:\Users\joaqu\Desktop\GPT for Discord\chatGPT-discord-bot-main\main.py", line 30, in <module>
    bot.run_discord_bot()
  File "C:\Users\joaqu\Desktop\GPT for Discord\chatGPT-discord-bot-main\src\bot.py", line 296, in run_discord_bot
    client.run(TOKEN)
  File "C:\Users\joaqu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\joaqu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\joaqu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Users\joaqu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 609, in login
    raise TypeError(f'expected token to be a str, received {token.__class__.__name__} instead')
TypeError: expected token to be a str, received NoneType instead

**Comment by elderprice** [comment]
raise TypeError(f'expected token to be a str, received {token.class.name} instead')
TypeError: expected token to be a str, received NoneType instead

This seems to be the issue. What do I need to change?

**Comment by Zero6992** [comment]
It appears that your Python environment is a bit messy, it is recommended to use conda to open a fresh environment for running the program

**Comment by elderprice** [comment]
# Discord Bot token https://discord.com/developers/applications
DISCORD_BOT_TOKEN=""

# Unofficial ChatGPT authentication (only Plus acoount) # https://chat.openai.com/api/auth/session
UNOFFICIAL_PAID=True
PUID=
ACCESS_TOKEN=
OPENAI_EMAIL=""
OPENAI_PASSWORD=""

# Official GPT-3.5 authentication
OPENAI_API_KEY=""

# Bard session_id
BARD_SESSION_ID=

# Optional setting
CHAT_MODEL=OFFICIAL # OFFICIAL(OPENAI API), UNOFFICIAL(CHATGPT WEBSITE), Bard, Bing
GPT_ENGINE=gpt-3.5-turbo # gpt-4(if you can access GPT-4 models)
LOGGING=True
REPLYING_ALL=False
DISCORD_CHANNEL_ID= # channel using to send the starting-prompt
REPLYING_ALL_DISCORD_CHANNEL_ID=

**Comment by elderprice** [comment]
Is it this one?

**Comment by elderprice** [comment]
> It appears that your Python environment is a bit messy, it is recommended to use conda to open a fresh environment for running the program

I downloaded miniconda - can that work?

And do you mean I use that instead of the command prompt terminal?

**Comment by Zero6992** [comment]
Did you follow the steps in the README and fill in the information in the `.env` file?

**Comment by elderprice** [comment]
> > # Discord Bot token https://discord.com/developers/applications
> 
> No, I'm asking you to provide the environment where you execute the code

I just used the Terminal/Command prompt on Windows.

**Comment by elderprice** [comment]
> Did you follow the steps in the README and fill in the information in the `.env` file?

Yup - I just took out the token and API because it's public.

**Comment by Zero6992** [comment]
And you do rename the file to `.env` right?

**Comment by elderprice** [comment]
> And you do rename the file to `.env` right?

Yes - actually, when I downloaded your latest file, it's already '.env'.

Although in an earlier version around March, I did see it was 'dev.env' and it had to be renamed.

**Comment by elderprice** [comment]
I did that and saved it to a new '.env' file. It still shows the same error as above. 
![Screenshot 2023-04-28 000445](https://user-images.githubusercontent.com/131581410/234920922-c3466b8e-276b-4410-a49a-4027592dd2d3.png)

**Comment by cleaner4** [comment]
I had the same issue an it turned out to be my .env file was the wrong file type you need to make sure it says .ENV under the file type column. it should change when you rename it on step 6. ive attached a screenshot showing how it should look.
![image](https://user-images.githubusercontent.com/114132844/235053723-51ee3c41-d8bf-4570-990b-caca4a6696b2.png)

**Comment by cleaner4** [comment]
Your .evn file is still a text file you need to rename it by removing the .txt from the end of the name so it says ".env" instead of ".env.txt" ive attached a screenshot showing how it should look notice the file type is "ENV file". Hope this helps.
![image](https://user-images.githubusercontent.com/114132844/235054857-cbb93dcc-a3b0-4eb3-afff-adf9ae9ca3ca.png)

**Comment by elderprice** [comment]
> I did that and saved it to a new '.env' file. It still shows the same error as above. ![Screenshot 2023-04-28 000445](https://user-images.githubusercontent.com/131581410/234920922-c3466b8e-276b-4410-a49a-4027592dd2d3.png)

it worked now. Thank you thank you thank you very much!
