### ISSUE TITLE
Bing credential isn't in .env?

### ISSUE THREAD

**Issue by aptidus** [Zero6992/chatGPT-discord-bot#364]
Hi I don't see Bing in the .env file anymore. Is that right?

**Comment by Zero6992** [comment]
Bing uses `config.json` to set up

**Comment by VXRKS** [comment]
I used a "cookie-editor" but still it seems I'm having problems with the Bing version could you possibly help with this?
![Error Code](https://user-images.githubusercontent.com/131906732/234663762-5651b07d-bdd9-470c-afbd-64498685dd76.PNG)

**Comment by Zero6992** [comment]
Have you renamed the file `cookies.dev.json` to `cookies.json`? 

Once that's done, export the cookies from Bing and paste them into the `cookies.json`
