### ISSUE TITLE
[REQUEST] intergrate hugging chat & open assiatnt

### ISSUE THREAD

**Issue by nekohacker591** [Zero6992/chatGPT-discord-bot#369]
https://huggingface.co/chat/

https://open-assistant.io/chat

its basically a very easy to jailbreak chat

it also requires no auth aka no sign in

also it has high quality as well based on open assistant speaking of such open assistant as well because that's what its based on

edit: open assistant requires auth but hugging does not

**Comment by Zero6992** [comment]
will check
