### ISSUE TITLE
Come across with this error after bot ran.

### ISSUE THREAD

**Issue by sslisen** [Zero6992/chatGPT-discord-bot#371]
Error while sending system prompt: invalid literal for int() with base 10: '# channel using to send the starting-prompt'
Traceback (most recent call last):
  File "E:\PycharmProjects\PythonProject\chatGPT-discord-bot-1.3.3\src\aclient.py", line 151, in send_start_prompt
    channel = self.get_channel(int(discord_channel_id))
ValueError: invalid literal for int() with base 10: '# channel using to send the starting-prompt'

This error appeared after running the bot, but the bot can be used normally, I don't understand what this error means.

![image](https://user-images.githubusercontent.com/59131974/234836238-3852884c-5a98-450d-a56f-c0a193b15942.png)

**Comment by Zero6992** [comment]
Delete the comment "# channel using to send the starting-prompt" part after `DISCORD_CHANNEL_ID=`

**Comment by sslisen** [comment]
> 

there is no such comment.
![image](https://user-images.githubusercontent.com/59131974/234862710-c9227c97-ee70-4ede-9eb7-a3253a6d355c.png)

**Comment by Zero6992** [comment]
in file `.env`

**Comment by sslisen** [comment]
> in file `.env`

It works.
Thank you sir.
