### ISSUE TITLE
Come across this error everytime.

### ISSUE THREAD

**Issue by TechySkills** [Zero6992/chatGPT-discord-bot#372]
I come across this error everytime i run the code:
C:\Users\alisu\OneDrive\Desktop\chatGPT-discord-bot-main\chatGPT-discord-bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\alisu\OneDrive\Desktop\chatGPT-discord-bot-main\chatGPT-discord-bot-main\main.py", line 1, in <module>
    from src import bot
ImportError: cannot import name 'bot' from 'src' (C:\Users\alisu\AppData\Local\Programs\Python\Python310\lib\site-packages\src\__init__.py)

![image](https://user-images.githubusercontent.com/82161063/234847619-9b6f5029-fe21-4d39-a637-5cdaed8dccf7.png)
I dont know what to do...

Plz help

**Comment by Zero6992** [comment]
#161

**Comment by killerjerick** [comment]
I had this issue briefly, only because I didn't copy over the "src" file that has the bot.py file inside

**Comment by Zero6992** [comment]
Lack of activity
