### ISSUE TITLE
Multi-threading problem  

### ISSUE THREAD

**Issue by programerr01** [Zero6992/chatGPT-discord-bot#375]
```2023-04-28 18:12:54 INFO     src.aclient -> Send system prompt with size 11
2023-04-28 18:12:54 ERROR    src.aclient -> Error while sending system prompt: 400 Bad Request (error code: 50006): Cannot send an empty message
Traceback (most recent call last):
  File "/home/ubuntu/chatGPT-discord-bot/src/aclient.py", line 166, in send_start_prompt
    await channel.send(response)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
2023-04-28 18:12:55 INFO     src.bot -> ChatGPT#8329  is now running!
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<aclient.process_messages() done, defined at /home/ubuntu/chatGPT-discord-bot/src/aclient.py:54> exception=RuntimeError("Task <Task pending name='Task-16' coro=<aclient.process_messages() running at /home/ubuntu/chatGPT-discord-bot/src/aclient.py:56>> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/home/ubuntu/chatGPT-discord-bot/src/aclient.py", line 56, in process_messages
    message, user_message = await self.message_queue.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
```
*No Output for /chat command*

**Comment by VXRKS** [comment]
I'm getting this same exact problem is there a way to fix? i'm not sure I see the solution here.

`Task exception was never retrieved
future: <Task finished name='Task-12' coro=<aclient.process_messages() done, defined at /home/vorks/Desktop/chatGPT-discord-bot-1.4.1/src/aclient.py:54> exception=TypeError("object Future can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/vorks/Desktop/chatGPT-discord-bot-1.4.1/src/aclient.py", line 56, in process_messages
    message, user_message = await asyncio.run_coroutine_threadsafe(
TypeError: object Future can't be used in 'await' expression`

**Comment by programerr01** [comment]
@VXRKS do put discord channel link in .env file

**Comment by VXRKS** [comment]
I have previously it just randomly stopped working and giving out that error. That's the only reason I took it out was due to that.

**Comment by Zero6992** [comment]
What is the environment you're running the code in, and python version?

**Comment by VXRKS** [comment]
I'm running in a vm on parrot.os/ linux and not sure on python version

**Comment by programerr01** [comment]
@VXRKS  it's debian with python 3.10

**Comment by programerr01** [comment]
@Zero6992 `message_queue.get()` is not able to get latest messages due to the fact that it's not on the main loop itself 
. i think it's something to do with discord client thread and the main thread. 
```
chatGPT-discord-bot/src/aclient.py", line 57, in process_messages
    message, user_message = await self.message_queue.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-15' coro=<aclient.process_messages() running at /home/ubuntu/chatGPT-discord-bot/src/aclient.py:57>> got Future <Future pending> attached to a different loop
```

**Comment by Zero6992** [comment]
I made some corrections in `bot.py`, but I'm not sure if it can fix this issue because I can't reproduce the error in my environment

**Comment by programerr01** [comment]
@Zero6992  if the code is pushed to the repo, i can give it a try and let you know

**Comment by Zero6992** [comment]
> @Zero6992 if the code is pushed to the repo, i can give it a try and let you know

already pushed

**Comment by programerr01** [comment]
@Zero6992  still having the same error 
**OS : Debian 5.10.162-1
python 3.9.2**
