### ISSUE TITLE
Create your own persona?

### ISSUE THREAD

**Issue by KangNguyenn** [Zero6992/chatGPT-discord-bot#377]
Is it possible to create a custom persona and set it as the default for startup or reset?

**Comment by iamxorum** [comment]
Just go in personas.py, create your own persona (follow an example from the ones already existent in the code) and set in "current_persona" the own one :)

**Comment by Zero6992** [comment]
> Just go in personas.py, create your own persona (follow an example from the ones already existent in the code) and set in "current_persona" the own one :)

correct

**Comment by RSerejo** [comment]
> Just go in personas.py, create your own persona (follow an example from the ones already existent in the code) and set in "current_persona" the own one :)

even using docker?
