### ISSUE TITLE
Bing response stops at "Searching the web for: x"

### ISSUE THREAD

**Issue by Boy0000** [Zero6992/chatGPT-discord-bot#378]
Not sure if there is any way around this but want something that is able to scan documentation
Bing seems like the only real alternative here but the response isnt followed up after it searches

![image](https://user-images.githubusercontent.com/62521371/235353822-38749cb2-e26a-4136-b9c5-96c0bb55980f.png)
![image](https://user-images.githubusercontent.com/62521371/235353825-f15f15fb-6e45-4bdd-b364-866d47250a42.png)

**Comment by Zero6992** [comment]
Thanks, the issue was fixed here https://github.com/acheong08/EdgeGPT/pull/363

I will release the fixed version soon
