### ISSUE TITLE
SUGGESTION : Reply modification

### ISSUE THREAD

**Issue by osu** [Zero6992/chatGPT-discord-bot#381]
Hey,

Instead of having a really old'ish reply form as this one : 

![image](https://user-images.githubusercontent.com/38815571/235486557-7bcfee62-bb5f-4c05-a55e-e8f0236475e3.png)

It would be better if we could also ping the actual bot and he'll take it as a request and will answer to it without having this embed thing where it pings you and tells you the model it's using.

**Comment by wilg** [comment]
i agree. i would also love it if there was a way for it to only chime in if it was useful

**Comment by Zero6992** [comment]
okay, I'll change this if it's better that way

**Comment by Zero6992** [comment]
add it
