### ISSUE TITLE
No reply error

### ISSUE THREAD

**Issue by HeroWarriors** [Zero6992/chatGPT-discord-bot#391]
The bot worked fine for more than a month, but now if I use any of the commands I get an error: Something went wrong, but if I use Dalle commands (/draw) than I get ERROR: Inappropriate request 😿.

**Comment by DinuNuggets** [comment]
What does your server log say?

**Comment by HeroWarriors** [comment]
Nothing. It says the same thing in `chatgpt_discord_bot.log`. I can't see any other log files.

**Comment by Zero6992** [comment]
Lack of activity
