### ISSUE TITLE
Bot not authenting through session tokens

### ISSUE THREAD

**Issue by greengeckowizard** [Zero6992/chatGPT-discord-bot#395]
Hi I'm trying to authenticate using the session puid and the other token and it's throwing this error. 
![image](https://github.com/Zero6992/chatGPT-discord-bot/assets/34012548/a9ac3a82-c5a2-4ad0-857b-fe5b0890602f)

**Comment by Zero6992** [comment]
`puid` and `session` token are for authentication in UNOFFICIAL models, but you switched to OFFICIAL model

**Comment by greengeckowizard** [comment]
![image](https://github.com/Zero6992/chatGPT-discord-bot/assets/34012548/aa711af8-bbd9-4bce-b1cc-ade7ddc56172)
I had setting set to true in the .env

UNOFFICIAL_PAID=True

**Comment by Zero6992** [comment]
What you need to switch to is the `Website ChatGPT`, and the image above shows you switching to the `OFFICIAL` Model

**Comment by Zero6992** [comment]
`UNOFFICIAL_PAID` is a deprecated environment name, please re-clone the latest version

**Comment by greengeckowizard** [comment]
With it set to official it gives this on the discord. 
![Screenshot_20230511_115026](https://github.com/Zero6992/chatGPT-discord-bot/assets/34012548/729a101e-783a-452c-a611-adfc06ded4fb)
