### ISSUE TITLE
Google Bard Error

### ISSUE THREAD

**Issue by Murat1Ahmet** [Zero6992/chatGPT-discord-bot#398]
Hey, 

When I use google bard i get this error, how can i fix it please, Pls help I'm new in coding

14.05 14:52:59 [Bot] 2023-05-14 15:52:59 [INFO]     src.aclient -> System prompt response:Google Bard encountered an error: b')]}\\'\\n\\n38\\n[["wrb.fr",null,null,null,null,[9]]]\\n56\\n[["di",195],["af.httprm",195,"1096111744077366754",8]]\\n25\\n[["e",4,null,null,131]]\\n'.

**Comment by Zero6992** [comment]
It's an unsolved issue, refer to here #358
