### ISSUE TITLE
Intents object has no attribute 'message_content'

### ISSUE THREAD

**Issue by Happylinzy** [Zero6992/chatGPT-discord-bot#4]
[root@VM-4-11-centos chatGPT-discord-bot]# python3 main.py
<Intents value=32509>
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import bot
  File "/root/chatGPT-discord-bot/bot.py", line 19, in <module>
    intents.message_content = True
AttributeError: 'Intents' object has no attribute 'message_content'

I checked the application and bot, the MESSAGE CONTENT INTENT is on.

**Comment by kotx** [comment]
Check your discord.py version?
