### ISSUE TITLE
Update web page context failed.

### ISSUE THREAD

**Issue by DinuNuggets** [Zero6992/chatGPT-discord-bot#402]
I always get this message when I've chatted with the "Bing AI" and I come back after several hours:
![IMG_20230517_074017](https://github.com/Zero6992/chatGPT-discord-bot/assets/61915816/c0ab4190-fe97-4cb1-b540-3f379d001f9b)
After that, only a `/reset` helps

**Comment by Zero6992** [comment]
The issue is most likely caused by outdated cookies, and the only way to resolve it is by refreshing them manually

You can try using the new optional feature `auto-login` to fetch cookies
