### ISSUE TITLE
Wrong response code

### ISSUE THREAD

**Issue by pardeike** [Zero6992/chatGPT-discord-bot#41]
Bot just stopped working. I stopped it, upgraded to v0.1.6 and also logged out and in with my browser and copied a new session_token into config.json.

Still when I start I get the same error as I got when it was failing before I quit the bot:

```
% python3 main.py
Traceback (most recent call last):
  File "/Users/ap/Projects/chatGPT-discord-bot/main.py", line 1, in <module>
    from src import bot
  File "/Users/ap/Projects/chatGPT-discord-bot/src/bot.py", line 3, in <module>
    from src import responses
  File "/Users/ap/Projects/chatGPT-discord-bot/src/responses.py", line 36, in <module>
    chatbot = Chatbot(config, conversation_id=None)
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 89, in __init__
    self.refresh_session()
  File "/opt/homebrew/lib/python3.10/site-packages/revChatGPT/revChatGPT.py", line 285, in refresh_session
    raise Exception("Wrong response code")
Exception: Wrong response code
```

**Comment by pardeike** [comment]
I created an issue in the dependency too: https://github.com/acheong08/ChatGPT/issues/260

**Comment by WaD45** [comment]
Same for me since a couple of minutes

**Comment by MohamedAl-Nassirat** [comment]
OpenAI has announced that chatGPT's services have been unstable today so I assume there is issues with their API as well.

**Comment by pardeike** [comment]
They have switched to cloudflare. The guys behind the api lib are working on it.

**Comment by TheAlchemist6** [comment]
Thank you for these updates. Greatly appreciate the work you guys did to have chatGPT available in this manner.

**Comment by jacky-chay** [comment]
I have already submited a pull request that have solved the issue. atleast on my side it's running well.

**Comment by Zero6992** [comment]
Sorry for noticing the update a bit late, I think everything should be back to work now
