### ISSUE TITLE
Bard Feature

### ISSUE THREAD

**Issue by Murat1Na** [Zero6992/chatGPT-discord-bot#410]
Since bard can create images now, can you add this feature

**Comment by Hikoboshi00** [comment]
I'm wondering about this too.

**Comment by Hikoboshi00** [comment]
I've found a workaround for this issue. 
Now, the bot will include the image link. Modify the function bard_handle_response in responses.py using the following code:

`async def bard_handle_response(message, client) -> str:
  response = await sync_to_async(client.chatbot.ask)(message)

  responseMessage = response["content"]
  images = response.get('images', [])

  if images:
    for img in images:
      responseMessage += f"\n![]({img})"

  return responseMessage`
