### ISSUE TITLE
Bing cookie expires, even with auto login

### ISSUE THREAD

**Issue by ZeroZeroOne-dev** [Zero6992/chatGPT-discord-bot#418]
After a fixed time (I'm guessing 12 hours) the bing token expires and the bot starts throwing errors: 

<img width="1019" alt="Screenshot 2023-06-02 at 23 48 18" src="https://github.com/Zero6992/chatGPT-discord-bot/assets/254635/ae9af837-a6c8-48d3-a7d0-644721b4580f">

Restarting the bot runs the auto login again and fixes the issue. 

Maybe a feature could be to automatically run the auto login again after some time has passed since the last time?

**Comment by Zero6992** [comment]
Due to 2FA, automatic login has become difficult to implement
