### ISSUE TITLE
google badr error

### ISSUE THREAD

**Issue by DifficultPhil** [Zero6992/chatGPT-discord-bot#423]
`2023-06-14 20:17:08 INFO     src.aclient -> System prompt response:Google Bard encountered an error: b')]}\'\n\n38\n[["wrb.fr",null,null,null,null,[9]]]\n57\n[["di",102],["af.httprm",102,"-455901786176413195",70]]\n25\n[["e",4,null,null,132]]\n'.`

how fix it?

**Comment by Zero6992** [comment]
refresh your cookies
