### ISSUE TITLE
Unofficial Mode Not Authenticating

### ISSUE THREAD

**Issue by sahinkerim** [Zero6992/chatGPT-discord-bot#427]
I write puid and access token but i am getting error when running /chat ... command.

"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys."

Can you help me?

**Comment by Zero6992** [comment]
you are using OFFICIAL model

**Comment by sahinkerim** [comment]
how can i use unofficial model?
