### ISSUE TITLE
ERROR    src.aclient -> Error while sending system prompt: 429 Too Many Requests

### ISSUE THREAD

**Issue by helsan74** [Zero6992/chatGPT-discord-bot#432]
Hello, 

When I start client 1.5.1 I get this error.

`ERROR    src.aclient -> Error while sending system prompt: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
`
Is this related to chatGPT?
Because if I run 1.2.1 it runs without any issue.
I'm trying to understand what setting is wrong.

Thanks

**Comment by Zero6992** [comment]
This issue is not related to the version you are using. This error message indicates that you are using OpenAI API but your account has either exceeded its payment limit or lacks a credit card setup

**Comment by Zero6992** [comment]
If you prefer not to use OpenAI API, go to the `.env` file and modify `CHAT_MODEL` to the model you want to use

**Comment by helsan74** [comment]
On 1.2.1 I'm using OFFICIAL without any issue.
But on 1.5.1 Also OFFICIAL but I get the error.

Same account on both.
