### ISSUE TITLE
gpt-4 is not working

### ISSUE THREAD

**Issue by TaijiMonster** [Zero6992/chatGPT-discord-bot#439]
I am already on plus paid subscription and according to openai website, api for gpt-4 has been turned on but still getting error:
ERROR MESSAGE: 404 Not Found {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

Is gpt-4 using the new api URL?

**Comment by mrostamii** [comment]
The same happened on my instance with the latest version (`main` branch):
> ERROR: Something went wrong, please try again later! 
```
ERROR MESSAGE: 404 Not Found {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

**Comment by Anonymous78e** [comment]
same

**Comment by mrostamii** [comment]
I can use the GPT-4 API after I got the email from OpenAI that my organization account has received this upgrade. But, it seems it's still GPT-3 since I asked a question about its version!

**Comment by Zero6992** [comment]
> I can use the GPT-4 API after I got the email from OpenAI that my organization account has received this upgrade. But, it seems it's still GPT-3 since I asked a question about its version!

This is the normal behavior of the GPT-4 API because its model is still based on GPT-3 and it hasn't been undergone pre-instruction like the GPT-4 on the website
