### ISSUE TITLE
cf_clearance

### ISSUE THREAD

**Issue by darku1337** [Zero6992/chatGPT-discord-bot#44]
C:\Users\\Desktop\DiscordChatGPT>python main.py
Traceback (most recent call last):
  File "C:\Users\\Desktop\DiscordChatGPT\main.py", line 1, in <module>
    from src import bot
  File "C:\Users\\Desktop\DiscordChatGPT\src\bot.py", line 3, in <module>
    from src import responses
  File "C:\Users\\Desktop\DiscordChatGPT\src\responses.py", line 29, in <module>
    "cf_clearance": data['cf_clearance'],
KeyError: 'cf_clearance'

**Comment by aW3ikun** [comment]
Follow the steps in the picture. You can check it.
Then, fill `config.json` with the value.
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/23023918/206975618-67329f3e-bd14-4582-8deb-802e4ce21540.png">

**Comment by Zero6992** [comment]
> Follow the steps in the picture. You can check it. Then, fill `config.json` with the value. <img alt="image" width="1773" src="https://user-images.githubusercontent.com/23023918/206975618-67329f3e-bd14-4582-8deb-802e4ce21540.png">

That's correct, I'm updating README

**Comment by Zero6992** [comment]
README has been updated
