### ISSUE TITLE
ERROR WHEN I CHAT WITH THE BOT

### ISSUE THREAD

**Issue by Anonymous78e** [Zero6992/chatGPT-discord-bot#443]
ERROR: Something went wrong, please try again later! 
 
ERROR MESSAGE: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by Marsedward** [comment]
me too

**Comment by adarshkumar714** [comment]
#### This error shows that your quota of API exceeded the request limit.
## To solve this error make a new open ai api key by going to the dashboard of open ai apis.
