### ISSUE TITLE
I can't see _puid Cookie

### ISSUE THREAD

**Issue by AlejandroBarreda** [Zero6992/chatGPT-discord-bot#444]
**I can't see _puid Cookie July 14, 2023.** 
Maybe is it only for a plus account?

![2023-07-14 203135](https://github.com/Zero6992/chatGPT-discord-bot/assets/39718917/f2a55c98-c8f8-48f9-a192-5edc2e43cbe3)

**Comment by Anonymous78e** [comment]
Same

**Comment by Zero6992** [comment]
Yes it's only available for plus account
