### ISSUE TITLE
UNOFFICIAL GPT-4 - IS THIS CURRENTLY SUPPORTED?

### ISSUE THREAD

**Issue by AndrewsPanda** [Zero6992/chatGPT-discord-bot#448]
I am trying to access unofficial GPT-4 using Plus account with correct PUID & ACCESS_TOKEN.

It is not currently working. Is this feature still supported/active?

**Comment by Zero6992** [comment]
Unofficial API endpoint is unstable, recommended to use the official version

**Comment by AndrewsPanda** [comment]
Thanks mate
