### ISSUE TITLE
Website ChatGPT authentication doesnt seem to work for me (while official API is)

### ISSUE THREAD

**Issue by pewpewso** [Zero6992/chatGPT-discord-bot#449]
I have set up both official API and website one,
Confirmed have GPT plus.

When I try to talk to model Website ChatGPT-3.5, it came back with error messages:

ERROR MESSAGE: Field missing. Details: {'conversation_id': '052bee3b-5a60-49b9-ac75-b97a2e0eefa6', 'message_id': 'cda8e58d-9c5a-4f00-9521-9a0f10cf39f4', 'is_completion': False, 'moderation_response': {'flagged': False, 'blocked': False, 'moderation_id': 'modr-7g8De1DiXQWBLKFr63VvkUzuKATuo'}}

Official GPT-3.5 works fine.

**Comment by dtpfl** [comment]
Try this fix https://github.com/Zero6992/chatGPT-discord-bot/pull/447
