### ISSUE TITLE
I can't use either BARD or Bing

### ISSUE THREAD

**Issue by I-m-a-Dude** [Zero6992/chatGPT-discord-bot#455]
"ERROR: Error while switching to the Bard model, check that you've filled in the related fields in .env."
But I did it as is said in the documentation(READ.ME)

**Comment by Zero6992** [comment]
Do you rename the `.env.example` to `.env`?

**Comment by I-m-a-Dude** [comment]
Yes I did it. That was the first thing I did after I cloned the repo. But I can't use it. Pardon me for late response

**Comment by pqr29** [comment]
i have the same error
