### ISSUE TITLE
Automatically trigger chat command when you ping the bot

### ISSUE THREAD

**Issue by ririko5834** [Zero6992/chatGPT-discord-bot#458]
When you ping the bot and after the ping you ask some question, send some text, automatically trigger chat command so you don't need to use slash cmd. Like `@ChatGPT Can you write nodejs express example code for me?` should trigger the ai chatbot.

**Comment by ririko5834** [comment]
Can you add this feature?

**Comment by ririko5834** [comment]
?

**Comment by Zero6992** [comment]
The user experience with slash commands is better than pinging the bot.

**Comment by Zero6992** [comment]
There is no plan to implement this feature
