### ISSUE TITLE
Autologin support for external browser

### ISSUE THREAD

**Issue by ririko5834** [Zero6992/chatGPT-discord-bot#459]
Can you add support for external browsers (using external ws URL) like https://www.browserless.io/ for the auto login feature? Its useful when you don't have chrome installed on machine where you host the bot, like docker containers, linux vps, ...

**Comment by ririko5834** [comment]
How do I use it when you completed it? Where do I enable to login with browserless?

**Comment by ririko5834** [comment]
@Zero6992

**Comment by Zero6992** [comment]
No need to login when using `/chat` command now

**Comment by Zero6992** [comment]
Major changes have been made to usage, please refer to the README.

**Comment by ririko5834** [comment]
I mean for the auto login it would be nice to be able to use external browser like browserless because for example I didn't success installing chrome on my linux and the auto login doesn't work then for me. And the cookie for google bard expires and it's annoying to obtain new cookie every time
