### ISSUE TITLE
Bing or Bard not authorized 

### ISSUE THREAD

**Issue by Arnost55** [Zero6992/chatGPT-discord-bot#468]
hello this error comes up when i want to do the auto login please help

![Snímek obrazovky (17)](https://github.com/Zero6992/chatGPT-discord-bot/assets/99980693/79b6fb04-8d35-4e85-9a35-a3b3041c6c01)

**Comment by Zero6992** [comment]
Due to 2FA, automatic login has become difficult to implement.
