### ISSUE TITLE
Conversation Signature error

### ISSUE THREAD

**Issue by Arnost55** [Zero6992/chatGPT-discord-bot#474]
![Snímek obrazovky (20)](https://github.com/Zero6992/chatGPT-discord-bot/assets/99980693/d8a6b0ed-7bf9-48fd-9b8d-839970e4dc5f)

**Comment by Arnost55** [comment]
please tell me what should i do

**Comment by Arnost55** [comment]
@Zero6992 please help

**Comment by Bonhovis** [comment]
Not sure how to upvote this issue, but hitting the exact same conversationSignature key error.

**Comment by Zero6992** [comment]
This is an issue from [EdgeGPT](https://github.com/acheong08/EdgeGPT)

**Comment by Zero6992** [comment]
Due to that repository no longer being maintained, I can only direct you to some forks made by other contributors. To implement the fix, you can locate your Python site-packages directory and replace the files in the `src` folder of `EdgeGPT` with the ones from the fork. 

https://github.com/brainboost/EdgeGPT

I have just tested this solution and it resolves the issue.

**Comment by Bonhovis** [comment]
That's amazing, thank you @Zero6992. Bot is now is now responding with Bing chat model in Discord. Really appreciate it 👏 

I am however now experiencing the same issue that someone else raised a couple of months ago re: the bot via Bing not providing working links (https://github.com/Zero6992/chatGPT-discord-bot/issues/456). Is there a way to also get this functioning  or is this something that's just not do-able?

**Comment by Arnost55** [comment]
thank you zero yu are a legend

**Comment by Iryn-e** [comment]
Works for me too! For those who don't quite know how to interpret Zero6992's advice here on where your "Python site-packages directory" is, (I'm new to python so it took me a bit to figure out on my own) refer to here for more information: "https://www.geeksforgeeks.org/get-location-of-python-site-packages-directory/"

Basically, to find where your "EdgeGPT" package is located, (if you've followed the installation step of "pip3 install -r requirements.txt") then you should do: `py -c "import site; print(site.getsitepackages())"`. After that, you should see the repository of where your packages are located. For me, it was located at "C:\Users\iryne\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT".

From there, just install this fork "https://github.com/brainboost/EdgeGPT", from there you can just replace everything in your package folder with the contents of the package's "src" folder. After that, it should work now.

**Comment by Zero6992** [comment]
Updated
