### ISSUE TITLE
[Request] - Add new engines in bot.py

### ISSUE THREAD

**Issue by TheFirstNoob** [Zero6992/chatGPT-discord-bot#478]
Add new engines with update for this commit: https://github.com/Zero6992/chatGPT-discord-bot/commit/0b60f76241c74c5fc62ff097a0cf467e41da9592

src/bot.py
here: https://github.com/Zero6992/chatGPT-discord-bot/blob/main/src/bot.py#L94
to here: https://github.com/Zero6992/chatGPT-discord-bot/blob/main/src/bot.py#L147

And add to documentation on /help command:
https://github.com/Zero6992/chatGPT-discord-bot/blob/main/src/bot.py#L150

Very thanks for your work <3

**Comment by Zero6992** [comment]
Updated
