### ISSUE TITLE
ChatGPT library blocks main thread

### ISSUE THREAD

**Issue by kotx** [Zero6992/chatGPT-discord-bot#5]
When sending requests via the ChatGPT Python library, the bot disconnects from Discord due to a timeout (since the client library is not asynchronous). Could use https://github.com/acheong08/ChatGPT/tree/async-dev for the async version of the library, or wait for it to be released.

**Comment by Zero6992** [comment]
I believe it would be best to update once the asynchronous version is released. What is your opinion on this?

**Comment by akshatj27** [comment]
> I believe it would be best to update once the asynchronous version is released. What is your opinion on this?

I believe it should use the current async-dev branch, it disconnecting from discord makes it quite unreliable at times

**Comment by Zero6992** [comment]
> > I believe it would be best to update once the asynchronous version is released. What is your opinion on this?
> 
> I believe it should use the current async-dev branch, it disconnecting from discord makes it quite unreliable at times

How can I import another branch of a lib before it releases a version?

**Comment by akshatj27** [comment]
https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by akshatj27** [comment]
> > > I believe it would be best to update once the asynchronous version is released. What is your opinion on this?
> > 
> > 
> > I believe it should use the current async-dev branch, it disconnecting from discord makes it quite unreliable at times
> 
> How can I import another branch of a lib before it releases a version?

https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by Zero6992** [comment]
I think there are still some unsolved issues on that branch.

**Comment by akshatj27** [comment]
> It might also be worth it to switch from `tls-client` and `requests` to the async equivalent, `aiohttp` (most discord.py bots use it). Plus `tls-client` [doesn't work under `aarch64`](https://github.com/FlorianREGAZ/Python-Tls-Client/issues/13):
> 
> ```
> OSError: /home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
> ```

can confirm about tls-client not working or aarch64. Tried it on oracle cloud and it throws that same error.

**Comment by arnav7633** [comment]
Do note the library "ts-client" is unsupported on manny platforms like arm which are quite extensively used in home servers

**Comment by Zero6992** [comment]
Keep track the version of httpx

[here](https://github.com/acheong08/ChatGPT/pull/110#issue-1480532046)

**Comment by Zero6992** [comment]
I released a new version that fixes this problem
