### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType [Error]

### ISSUE THREAD

**Issue by greengeckowizard** [Zero6992/chatGPT-discord-bot#50]
![Screenshot 2022-12-12 170033](https://user-images.githubusercontent.com/34012548/207174477-ff94ed03-4f66-44af-8e01-4c565e8209ce.png)

After I fill out config.json 

and run the main.py with "python3 main.py" I get error
I also install the dependencies with "pip install -r requirements.txt"

**Comment by Zero6992** [comment]
What revChatGPT you used? It's should be `revChatGPT==0.0.a42`

refer to [#281](https://github.com/acheong08/ChatGPT/issues/281)

**Comment by Zero6992** [comment]
Do not fill `cf-clearance` and `user-agent` in version `0.0.a42`

**Comment by greengeckowizard** [comment]
> What revChatGPT you used? It's should be `revChatGPT==0.0.a42`
> 
> refer to [#281](https://github.com/acheong08/ChatGPT/issues/281)

Yes I am using that version of revChatGPT

**Comment by greengeckowizard** [comment]
> Do not fill `cf-clearance` and `user-agent` in version `0.0.a42`

I'll try this thanks

**Comment by greengeckowizard** [comment]
> Do not fill `cf-clearance` and `user-agent` in version `0.0.a42`

I tried and I'm getting error still this is what it says 
![ss](https://user-images.githubusercontent.com/34012548/207225372-0400e6a4-8284-4442-b280-d7df31d5ae65.png)

**Comment by greengeckowizard** [comment]
I found the fix to the issue I didn't have Google Chrome installed so it wasn't opening it for authentication.
