### ISSUE TITLE
Add support for Gemini

### ISSUE THREAD

**Issue by djdoolky76** [Zero6992/chatGPT-discord-bot#500]
It seems like the bard option with __Secure-1PSID no longer works for me since it has been rebranded to Gemini. 

![image](https://github.com/Zero6992/chatGPT-discord-bot/assets/30578879/e1370c37-8213-48ef-9346-17f984342af4)

**Comment by Zero6992** [comment]
supported Now

**Comment by shinyflvres** [comment]
Gemini still not supported.
