### ISSUE TITLE
draw image

### ISSUE THREAD

**Issue by lavanda131** [Zero6992/chatGPT-discord-bot#504]
gemeni

Something Went Wrong, try again later.

Error Message:Create images failed: we can't create your images right now

openai

Something Went Wrong, try again later.

Error Message:
---------------------
Could not determine browser executable.
---------------------
Make sure your browser is installed in the default location (path).
If you are sure about the browser executable, you can specify it using
the browser_executable_path='/path/to/browser/executable parameter.

bing

Something Went Wrong, try again later.

Error Message:Create images failed: we can't create your images right now

**Comment by Zero6992** [comment]
Install Google Chrome for providers with webdriver

**Comment by Zero6992** [comment]
`Error Message: "Create images failed: we can't create your images right now."`
This issue originates from the API endpoint, not the codebase
