### ISSUE TITLE
ClientResponseError: 401, message='Unauthorized', url=URL('https://chat.openai.com/backend-api/models')

### ISSUE THREAD

**Issue by lavanda131** [Zero6992/chatGPT-discord-bot#506]
2024-03-10 22:35:13 INFO     src.log -> .lavanda. : /draw [banan 8к] in (Direct Message with .lavanda.)
OpenaiChat: Load default_model failed
ClientResponseError: 401, message='Unauthorized', url=URL('https://chat.openai.com/backend-api/models')
Open browser with config dir: C:\Users\User\AppData\Local\g4f\g4f
Successful: The process "undetected_chromedriver.exe", with ID 15728, has been completed.
2024-03-10 22:35:29 INFO     src.log -> .lavanda. :

the response from the bot in the discord:

Something Went Wrong, try again later.

Error Message:

**Comment by Zero6992** [comment]
you need plus account for generating image in openai model
