### ISSUE TITLE
You Provider isn't workin

### ISSUE THREAD

**Issue by TheColonists** [Zero6992/chatGPT-discord-bot#507]
Hello, so originally You Provider was working but all of a sudden I am now getting the following error.
<img width="490" alt="image" src="https://github.com/Zero6992/chatGPT-discord-bot/assets/164422493/d48c451d-b524-40be-b33e-db13fab051da">

**Comment by Zero6992** [comment]
provider issue please check https://github.com/xtekky/gpt4free
