### ISSUE TITLE
CHINESE?

### ISSUE THREAD

**Issue by ryudious** [Zero6992/chatGPT-discord-bot#514]
WHY is it in CHINESE when it speaks...

**Comment by 1337haxx0r** [comment]
that indeed happened when I switched to gpt-4o, but if i set `MODEL=gpt-4-turbo` - it works fine

**Comment by Zero6992** [comment]
Are you using the OpenAI API or the default settings?

**Comment by ryudious** [comment]
I used my key.  But it isn't working. I use my GPT Plus one.  Or is it the other API key that charges fir use?  I put it under the thing with "dhhdhdhxhdhdhd"

**Comment by Zero6992** [comment]
provider issue, just updated
