### ISSUE TITLE
The redundant log message.

### ISSUE THREAD

**Issue by aW3ikun** [Zero6992/chatGPT-discord-bot#58]
```bash
@aW3ikun ➜ /workspaces/chatGPT-discord-bot (main ✗) $ xvfb-run python3 main.py
2022-12-14 05:49:51 ERROR    __main__ -> revChatGPT version 0.0.44 is installed but does not match the requirements.
NoneType: None
```
`NoneType: None` is a redundan message.
When using `logger. exception()` to print notice, the exception info is added to the logging message. However, it's just a reminder to users, it does not cause an exception, and the output is always `NoneType: None`. 
Reference: https://docs.python.org/3/library/logging.html#logging.Logger.exception

As a result, `logger.error()` replaces `logger.exception()`.

I will fix it next PR.

**Comment by Zero6992** [comment]
I am not very familiar with logger related , thank you
