### ISSUE TITLE
starting-prompt.txt is great! but.. where does it send the first message/reply from openai to?

### ISSUE THREAD

**Issue by badjoerichards** [Zero6992/chatGPT-discord-bot#64]
Hello Zero!

Love starting-prompt.txt ! but the first message, 

1. where does it get sent to?
2. Are we able to specify a #channelid for the discord server to send the first message to or something?

Thank you for the great work!

**Comment by Zero6992** [comment]
I'm really glad you like this feature
1. It only sends the first message to the terminal
2. Great suggestion! I'll start trying to see if it's possible.

**Comment by Zero6992** [comment]
You can now set your discord_channel_id to specify a channel for the bot to send the first message to
