### ISSUE TITLE
is there any way to run it on replit?

### ISSUE THREAD

**Issue by RizkyNugroho666** [Zero6992/chatGPT-discord-bot#65]
i tried to run it on replit and it says Permission Denied, but it works perfectly on my desktop

**Comment by Zero6992** [comment]
Hi, I'm not very familiar with replit, maybe you could try running docker on it?

**Comment by takomine** [comment]
I used to run the bot on Replit, but now it's not possible because of Playwright. You can chmod Playwright but you'll end up having problems with glibc.

**Comment by Zero6992** [comment]
Using OpenAI official GPT-3 API now

**Comment by takomine** [comment]
Confirmed working again on replit
