### ISSUE TITLE
embed not working

### ISSUE THREAD

**Issue by KKonaNN** [Zero6992/chatGPT-discord-bot#89]
code embed is getting on normal msg not on a code embed like ```py print()```

**Comment by KKonaNN** [comment]
[](https://cdn.discordapp.com/attachments/862107170232467476/1054503968983744522/image.png)

**Comment by aW3ikun** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/23023918/208704318-d1eaf740-2055-478f-a97e-b7897e492543.png">
Bot's response is the same as msg from playground of OpenAI.  
Maybe you could add a feature to filter code to highlight code blocks.

**Comment by Zero6992** [comment]
GPT3 model does not provide this feature
