### ISSUE TITLE
Different kind of bot reply to the message. Not a ChatGPT bot.

### ISSUE THREAD

**Issue by sahalsaad** [Zero6992/chatGPT-discord-bot#90]
Hi, 

Seems like I get the reply from not ChatGPT bot. The bot is not smart as the one in the ChatGPT demo. It could not answer programming questions correctly.

![image](https://user-images.githubusercontent.com/22321353/208550923-471162c5-f24b-47e2-8621-0b5fb25281e1.png)

Is there something extra to do to get the correct bot?

Thanks

**Comment by LynBean** [comment]
The model used by this repo is "text-davinci-003". There's other different models can be found in here [https://beta.openai.com/docs/api-reference/completions/create#completions/create-model](url)

**Comment by sahalsaad** [comment]
> text-davinci-003

Hi, thanks for the reply. Do you know which model was used for the image shown in the readme?

**Comment by LynBean** [comment]
@sahalsaad  I have created the same chat bot, but with much more functions included your issues, kindly checkout my project, https://github.com/LynBean/chatgpt-in-discord

**Comment by sahalsaad** [comment]
> @sahalsaad I have created the same chat bot, but with much more functions included your issues, kindly checkout my project, https://github.com/LynBean/chatgpt-in-discord

i tried it, the response is quite similar to this project. Not similar to the one in the ChatGPT website. Thanks ya

**Comment by LynBean** [comment]
> i tried it, the response is quite similar to this project. Not similar to the one in the ChatGPT website. Thanks ya

I see .. you are asking for the bot to respond your message based on reference of previous messages?

I will try to make this feature on my own project, stay tuned ☺️

**Comment by Zero6992** [comment]
I am only able to use the OpenAI GPT3 model currently due to some issues. If a stable ChatGPT API becomes available, I will update ASAP

btw, sorry for responding late, it's the final week of school
