### ISSUE TITLE
Feature Request - Code formated as code

### ISSUE THREAD

**Issue by tmarquespt** [Zero6992/chatGPT-discord-bot#92]
Can we leverage the discord code formatting with ``` code ``` in order to display the code inside the code box?
like this:
![image](https://user-images.githubusercontent.com/38387300/208905923-851d956e-8efb-4d3b-89b3-500d2ace6d46.png)

instead of this:
![image](https://user-images.githubusercontent.com/38387300/208905970-2d82449a-9fcd-4de8-af22-ad715d1b1199.png)

Great work with this discord integration 👍

**Comment by Zero6992** [comment]
Identifying code segments is not easy, but it's easy to make mistakes if we hard code them

OpenAI API doesn't have an embedded option currently and only ChatGPT on the website writes out code segments in an embedded format

**Comment by Zero6992** [comment]
I will update if a stable API become available

Thank you for your suggestion though

**Comment by tmarquespt** [comment]
Fair enough 👍. Thanks for the reply.
