### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by H0Im** [Zero6992/chatGPT-discord-bot#93]
Hi!

I'm having some issues getting it to work here on my end, which is most likely (definitely) due to misconfiguration.

 So I initially just created the docker-compose.yml in my repo (I'm running Linux, Distro=Ubuntu)
 Copied your docker-compose.yml and ran it, got the following message `ERROR: Service 'chatgpt-discord-bot' failed to build : Build failed`
 
 I then git-cloned the project to a local repo which included all the files.
 I THEN ran `docker-compose up` which had promising results where it carried out the dockerfile instructions.
 
 However when I look in the logs I got this message 
`Traceback (most recent call last):`
`  File "main.py", line 1, in <module>`
`    from src import bot`
`  File "/DiscordBot/src/bot.py", line 3, in <module>`
`    from src import responses`
`  File "/DiscordBot/src/responses.py", line 18, in <module>`
`    config = get_config()`
`  File "/DiscordBot/src/responses.py", line 12, in get_config`
`    with open(config_path, 'r') as f:`
`IsADirectoryError: [Errno 21] Is a directory: '/DiscordBot/config.json'`
` *  Terminal will be reused by tasks, press any key to close it. `

Is there something obvious that I'm doing wrong?

**Comment by H0Im** [comment]
Renaming the config.dev.json -> config.json did the trick.
Could possibly add this in the wiki or change the name in the repo?

**Comment by Zero6992** [comment]
I mentioned in README in the step of setting up the discord bot, but I realized that some people might skip over that part

I'll rewrite it to the first step to make sure people don't miss it

**Comment by Zero6992** [comment]
Btw, new version was out

fix some asynchronous issues

**Comment by H0Im** [comment]
> I mentioned in README in the step of setting up the discord bot, but I realized that some people might skip over that part
> 
> I'll rewrite it to the first step to make sure people don't miss it

You are absolutely right, my bad! I skimmed through and didn't notice it.
