### ISSUE TITLE
Session context

### ISSUE THREAD

**Issue by mujehoxe** [Zero6992/chatGPT-discord-bot#98]
The bot should take the whole session into consideration while trying to answer, but currently it is only taking the last prompt

what is the version history of messenger that you know off? - @me

1.0 (August 2016): Initial Release 
2.0 (August 2017): Group Chat, Video Calls, and GIF Support 
2.1 (October 2017): Improved Contacts List 
2.2 (July 2018): Bug Fixes and Performance Enhancements 
2.3 (August 2018): Improved Chat Interface 
2.4 (November 2018): Ability to Send and Receive Files 
2.5 (December 2018): Improved Media Sharing 
2.6 (August 2019): Improved Call Quality 
2.7 (March 2020): Dark Mode Support 
2.8 (August 2020): Improved Voice and Video Quality.

what are their version codes? - @me

The version codes of Android are usually a combination of numbers and letters. It is usually four numbers separated by a dot. For example, the version code for Android 8.0 is 8.0.0.

what is the version code for messenger 2.8? - @me

The version code for Messenger 2.8 is 16051916.

what about 2.7? @me

Python 2.7 is the final version of the Python 2 series and was released in 2010. It is still widely used, but Python 3 is the recommended version to use.

**Comment by variousred** [comment]
I'm having this issue as well. Combing through the openai docs, i wonder if it has to do with passing an end-user ID ? Nothing in the documentation mentions these being useful for conversation context however.
https://beta.openai.com/docs/guides/safety-best-practices/end-user-ids

**Comment by variousred** [comment]
Found this:

**Comment by variousred** [comment]
Basically you have to remember the conversation so far yourself (client side) and pass that prepended to the latest query - so the entire context is built up and sent each time.

**Comment by variousred** [comment]
It kind of makes the starting prompt useless.

**Comment by mujehoxe** [comment]
Makes sense, however it seems difficult complicated, for instance how would it know it it only needs to answer the last prompt if there were multiple questions during the session, meaning we are going to see more identical answers.

**Comment by variousred** [comment]
It knows to only answer the last question

**Comment by sudoskys** [comment]
I made an interesting solution to temporarily replace chatGPT: https://github.com/sudoskys/openai-kira

**Comment by Zero6992** [comment]
Currently using GPT-3 model, awaiting the official release of ChatGPT API
